import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {performance} from 'node:perf_hooks';
import {pathToFileURL} from 'node:url';
import Ajv from 'ajv';
const E='cpa_uploader/analysis/reviews/point-review-and-publication-2026-09-11/efficient-verification-2026-09-12',dir=E+'/b/performance-review-v1';
const output=dir+'/measurement.json';assert(!fs.existsSync(output));
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const mf=E+'/candidate-v4/grading-manifest.json',mb=fs.readFileSync(mf),mh=sha(mb);assert.equal(mh,'50287a7729405c6157c962ee30f58b683fb5b58cfcc93d299e20e854e8365d1c');const manifest=JSON.parse(mb);
const savedRuntime=manifest.code_files.map(i=>{assert.equal(sha(fs.readFileSync(i.file)),i.sha256);return i;});
const importsStart=performance.now();const core=await import(pathToFileURL(path.resolve('cpa_uploader/questionEfficientReview.ts')).href);const importsMs=performance.now()-importsStart;
const originGroups=new Map();for(const r of manifest.reused_observations){const list=originGroups.get(r.origin_manifest.file)??[];list.push(r);originGroups.set(r.origin_manifest.file,list);}assert.equal(originGroups.size,2);
const old=[...originGroups].find(([f])=>f.includes('/candidate-v1/'))[1],newer=[...originGroups].find(([f])=>f.includes('/candidate-v3/'))[1];
const chosen=[old[0],...newer.slice(0,19)];assert.equal(chosen.length,20);
const originalRead=fs.readFileSync,originalCompile=Ajv.prototype.compile;const context=core.createEfficientValidationContext();
let reads=0,bytes=0,readMs=0,compiles=0,compileMs=0;const files=new Map();
fs.readFileSync=function(...args){const start=performance.now();const result=Reflect.apply(originalRead,this,args);readMs+=performance.now()-start;reads++;const size=Buffer.isBuffer(result)?result.length:Buffer.byteLength(result);bytes+=size;const key=typeof args[0]==='string'?path.resolve(args[0]):String(args[0]);const stats=files.get(key)??{count:0,bytes:0};stats.count++;stats.bytes+=size;files.set(key,stats);return result;};
Ajv.prototype.compile=function(...args){const start=performance.now();try{return Reflect.apply(originalCompile,this,args);}finally{compiles++;compileMs+=performance.now()-start;}};
const rows=[],seenOrigins=new Set();const startedAt=new Date().toISOString(),start=performance.now(),cpuStart=process.cpuUsage();
try{for(const reuse of chosen){const cold=!seenOrigins.has(reuse.origin_manifest.file),before={reads,bytes,readMs,compiles,compileMs},at=performance.now();core.validateReusableEfficientObservation(reuse,manifest,context,process.cwd());const elapsed=performance.now()-at;seenOrigins.add(reuse.origin_manifest.file);rows.push({entry_id:reuse.entry_id,observation:reuse.observation,origin_manifest:reuse.origin_manifest,cold_origin:cold,elapsed_ms:elapsed,read_calls:reads-before.reads,read_bytes:bytes-before.bytes,read_ms:readMs-before.readMs,ajv_compile_calls:compiles-before.compiles,ajv_compile_ms:compileMs-before.compileMs,pass:true});console.log(JSON.stringify({checked:rows.length,entry:reuse.entry_id,cold,ms:Math.round(elapsed)}));}}
finally{fs.readFileSync=originalRead;Ajv.prototype.compile=originalCompile;}
const elapsed=performance.now()-start,cpu=process.cpuUsage(cpuStart);const guardStart=performance.now();core.assertEfficientEvidenceUnchanged(context);const finalGuardMs=performance.now()-guardStart;
assert.equal(sha(fs.readFileSync(mf)),mh);for(const i of savedRuntime)assert.equal(sha(fs.readFileSync(i.file)),i.sha256);
const warm=rows.filter(r=>!r.cold_origin),cold=rows.filter(r=>r.cold_origin);const avg=warm.reduce((n,r)=>n+r.elapsed_ms,0)/warm.length;
const report={version:1,artifact_type:'read_only_actual_reuse_performance_sample',created_at:new Date().toISOString(),started_at:startedAt,api_calls:0,db_calls:0,production_changes:0,manifest:{file:mf,sha256:mh},method:'Twenty actual immutable observations validated once with the current public validateReusableEfficientObservation and one shared context. fs.readFileSync and Ajv.compile were transparent local-process timing wrappers forwarding unmodified arguments/results and restored afterwards. No mock/raw replacement or acceptance receipt.',environment:{node:process.version,platform:process.platform,arch:process.arch,cpu_count:os.cpus().length,working_directory:process.cwd(),concurrent_activity:'Root stated run-v3 preflight/execution may be active; machine load is not controlled. OS file cache not flushed.'},selection:{total_reuses:735,observations:20,origin1_count:1,origin2_count:19,cold_origin_calls:2,warm_context_calls:warm.length,scope_exclusion:'Does not execute full validateBatch, validateAuthoringBank, promotion or import.'},summary:{module_import_ms:importsMs,validation_elapsed_ms:elapsed,cpu_user_ms:cpu.user/1000,cpu_system_ms:cpu.system/1000,cold_origin_ms:cold.reduce((n,r)=>n+r.elapsed_ms,0),warm_mean_ms:avg,warm_min_ms:Math.min(...warm.map(r=>r.elapsed_ms)),warm_max_ms:Math.max(...warm.map(r=>r.elapsed_ms)),read_calls:reads,read_bytes:bytes,read_ms:readMs,unique_read_files:files.size,ajv_compile_calls:compiles,ajv_compile_ms:compileMs,final_shared_guard_ms:finalGuardMs,guarded_files:context.files.size,all20_passed:rows.every(r=>r.pass),rough_735_one_replay_ms:cold.reduce((n,r)=>n+r.elapsed_ms,0)+(735-cold.length)*avg,projection_warning:'Linear warm-sample extrapolation is a risk indicator only; full batch replays reused evidence a second time and adds other validation/guards. Final staging wall time is authoritative.'},top_read_files:[...files].map(([file,s])=>({file:path.relative(process.cwd(),file).replaceAll('\\','/'),...s})).sort((a,b)=>b.bytes-a.bytes).slice(0,15),rows,runtime: savedRuntime,full_validation_measured:false};
fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({output,sha256:sha(fs.readFileSync(output)),summary:report.summary},null,2));
