import fs from 'node:fs';
import {createHash} from 'node:crypto';
const batch='cpa_uploader/drafts/case-trio-next-2026-09-14',dir=`${batch}/a`;
const hash=v=>createHash('sha256').update(v).digest('hex'),fileHash=f=>hash(fs.readFileSync(f)),read=f=>JSON.parse(fs.readFileSync(f,'utf8'));
const s=read(`${dir}/sets.json`)[0],d=read(`${dir}/design.json`)[0],qa=read(`${dir}/qa.json`),r=read(`${dir}/review.json`),catalog=read(`${batch}/source-catalog.json`),bank=read(`${batch}/bank-before.json`);
const declared={
'sets.json':'6e1e1444fc5cb2a57aeee5021699d7a5cdb7bb9535933be0d8b9655667e06802',
'design.json':'5f645585d6bdbbd45b7b1f678b0a5a860fe88c5a77f7a72c13756040d1ed41fe',
'review.json':'92a8bdec705b51bd4afceb7bb0c5c49eaa654c2ebe41898efae495d0737862b3',
'qa.json':'bd83122109cf73146883836a6876f7aaa93d2f6541fb6c14e73e3980a73e5865'};
for(const[f,h]of Object.entries(declared))if(fileHash(`${dir}/${f}`)!==h)throw Error(`author file changed ${f}`);
const common={fact_style:'최초 발견·미해결 충돌·최종 불신이라는 세 시점을 구별한다. 부모의 계약 해지 설명·은행 자료·누락 지시·최종 신뢰성 결론을 지우면 같은 만점 답안이 성립하지 않는다.',scope:'각 물음의 명시된 시점과 대상만 평가하며 최초 충돌 단계에 최종 의견거절 결론을 앞당겨 적용하지 않는다.',points:'독립 판단·구체 절차 또는 독립 평가 대상별 정수1점이다. 동일 문장을 반복하거나 한 절차의 문서요청·대조라는 부분을 각각 별도 점수로 늘리지 않는다.',qa:'대표 partial/wrong 각1개 및 수동 model/empty/partial/wrong/reverse_partial/implicit/repetition/general_only 총8개를 criterion별로 직접 대조했다.',source:'등록 직접 인용과2026 공식본문을 아래 source_checks·official_reading 범위에서 대조했다. 자동 의존성 완결 여부만으로 판정하지 않았다.',topic:'실제 요구에 맞춰 서면진술12와 감사증거08 또는 감사의견15를 연결한다.',nonduplication:'현재580 기준서형 및 pilot-12-010, 과거 미제공 초안과 실제 발문·모범·배점기준을 비교했다. 미제공이나 일반목록을 제공된 진술과 실제 증거의 불일치 적용으로 바꾸었고, 단순 이름 교체에 그치지 않는다.'};
const rationales={
sub1:{answer:'580.17에 따라 불일치의 해결을 시도해야 한다. 두 사람의 서명만으로 은행 계약서와 연말 해지 설명 사이의 충돌을 해소할 수 없고, 은행의 해지 여부·효력일 확인 등 한 구체 절차가 그 목적에 적합하다.',boundary:'구체 은행 확인을 제시하면 종결 불가가 함축되어2점이다. 명시적 동의+적합한 은행 확인은 절차1점만 유지한다. 일반적인 불일치 해결 필요는 종결 불가1점만 가능하고 구체절차 점수는 없다.',points:'판단1+계약상태 구체확인1=2. 같은 확인절차의 문서요청과 은행대조를 추가 분해하지 않는다.'},
sub2:{answer:'580.16·17은 성실성 우려를 경영진 진술과 감사증거 일반의 신뢰성에 연결한다. 실제 누락 지시에 따른 성실성 재고, 같은 재무이사의 제품보증 구두설명, 그가 제공한 연령분석표의 완전성·신뢰성을 구별한 답이 적합하다.',boundary:'실제 거짓이라고 확정되지 않은 제품보증 진술을 자동 거짓으로 취급하지 않는다. 성실성 유지라는 반대 결론이 있어도 두 적합한 신뢰성 평가는2점으로 보존된다. 일반목록만으로는 구체자료 적용3기준을 충족하지 않는다.',points:'성실성1+제품보증 진술1+연령분석표1=3. 서로 다른 대상이 독립적이며 각 평가와 확인절차는 대안 표현으로 중복 가점하지 않는다.'},
sub3:{answer:'서명은 모두 제공되었지만 성실성 의문으로580.10·11의 핵심 책임진술까지 믿을 수 없다는 최종 결론이 주어져580.20(a)를 적용한다. A26·A7 및705.9에 따라 다른 일부 계정의 증거로 대체할 수 없는 전반적 증거입수 부재이므로 의견거절이 맞다.',boundary:'580.20(b)의 미제공과 구별한다. 단순 충돌이나 어느 진술 하나의 문제만으로 자동 거절하는 답과 다르다. 명시적 한정의견+올바른 핵심진술 불신의 전반적 이유는 이유1점만 보존한다.',points:'의견1+핵심진술 불신에 따른 전반적 증거입수 부재 이유1=2. 서명 존재·대체불가·전반성은 독립 추가점수가 아니다.'}
};
const rows=s.subquestions.map(q=>{const expected=d.subquestions.find(x=>x.subquestion_id===q.id).local_regression_expectations;for(const x of expected){const points=q.criteria.filter(c=>x.met_criterion_ids.includes(c.id)).reduce((n,c)=>n+c.max_points,0);if(points!==x.expected_points)throw Error(`bad expected sum ${q.id}/${x.kind}`);}return{subquestion_id:q.id,reviewed_question_sha256:hash(JSON.stringify(q)),criteria:q.criteria.map(c=>({id:c.id,points:c.max_points,claim:c.claim,verdict:'pass'})),checks:Object.entries({...common,answer:rationales[q.id].answer}).map(([check,reason])=>({check,verdict:'pass',reason})),point_verdict:rationales[q.id].points,qa_reason:rationales[q.id].boundary,representative_qa:qa.filter(x=>x.subquestion_id===q.id),boundary_review:expected.map(x=>({kind:x.kind,answer:x.answer,expected_points:x.expected_points,met_criterion_ids:x.met_criterion_ids,independent_verdict:'pass'})),unresolved:[]};});
const sourceChecks=s.source_refs.map(ref=>{const u=catalog.units.find(u=>u.id===ref.id);if(!u||!fs.readFileSync(ref.file,'utf8').includes(ref.source_quote))throw Error(`bad quote ${ref.id}`);return{source_ref_id:ref.id,file:ref.file,file_sha256:fileHash(ref.file),source_quote_sha256:hash(ref.source_quote),registered_unit_content_hash:u.contentHash,quote_exact_substring:true,paragraph:u.paragraph,verdict:'pass'};});
const official=d.official_edition_comparison.map(x=>({key:x.key,file:x.official_file,file_sha256:fileHash(x.official_file),start_line:x.start_line,end_line:x.end_line,pdf_page:x.pdf_page,quote:fs.readFileSync(x.official_file,'utf8').split(/\r?\n/).slice(x.start_line-1,x.end_line).join('\n'),registered_file:x.registered_file,registered_quote_sha256:x.registered_quote_sha256,verdict:'pass',reason:'공식 텍스트의 해당 문단을 직접 읽어 독립적으로 의미와 조건을 대조했다. PDF602/603/604/609/610/771은 이번 peer가 재사용 이미지를 직접 보았다. 605 A7은 텍스트를 직접 대조했으며 peer의 시각 대조로 확대하지 않는다.'}));
const learning=d.source_locations.map(x=>({...x,file_sha256:fileHash(x.file),read_quote:fs.readFileSync(x.file,'utf8').split(/\r?\n/).slice(x.start_line-1,x.end_line).join('\n'),verdict:'pass',reason:x.original.startsWith('cpa_exam')?'실제 수록2020 문제3 물음3(2)는 미제공 대응이며 감사의견 영향 고려는 예시로 제외되어 있다. 새 불일치 사례의 직접 출제 빈도·범위로 넓히지 않고 adjacent로 연결한 것이 맞다.':'고급연습2023 GS2 문제8 물음2의 실제 요구는 서면진술을 얻는 이유이다. 새 증거충돌 해결절차와 직접 같지 않아 adjacent가 맞다. 해설A10 표기는 현행A1 본문과 대조해야 한다.'}));
const sourceFiles=read(`${dir}/source-files.json`).map(x=>({...x,actual_sha256:fileHash(x.file),hash_matches:fileHash(x.file)===x.sha256,peer_read_scope:'해시는 전 목록에서 검사했다. 직접 내용 대조 범위는 본 장부의 source_checks·official_reading·learning_reading·comparison_reading에 한정한다.'}));
if(sourceFiles.some(x=>!x.hash_matches))throw Error('source file changed');
const comparisonIds=['pilot-12-010','pilot-12-003','std-points-20260914-ae160de36d94','std-points-20260914-e7a3730d6484','std-points-20260914-c82d262bd6a8','std-points-20260914-1cae16e579d0'];
const comparison=comparisonIds.map(id=>{const x=bank.find(s=>s.id===id);if(!x)throw Error(id);return{set_id:id,title:x.title,content_hash:hash(JSON.stringify(x)),questions:x.subquestions.map(q=>({id:q.id,prompt:q.prompt,model_answer:q.model_answer,criteria:q.criteria.map(c=>({id:c.id,claim:c.claim,points:c.max_points}))})),verdict:'different_applied_scope'};});
const files=['sets.json','design.json','review.json','qa.json','source-files.json','coverage-proposals.json','validation.json','spec.json'];
const output={version:1,created_at:new Date().toISOString(),reviewer_id:'agent:/root/followup_sources_b',author_id:'agent:/root/next_cases_early',method:'independent_agent_content_source_points_and_qa_review',human_review_performed:false,actual_model_grading:'not_run',api_calls:0,set_id:s.id,reviewed_files:Object.fromEntries(files.map(f=>[`${dir}/${f}`,fileHash(`${dir}/${f}`)])),reviewed_set_content_hash:hash(JSON.stringify(s)),summary:{sets:1,questions:3,criteria:7,points:7,facts_chars:[...s.shared_context.facts.map(f=>f.text).join('\n')].length,checks:rows.reduce((n,r)=>n+r.checks.length,0),representative_qa:qa.length,manual_boundary_cases:rows.reduce((n,r)=>n+r.boundary_review.length,0),unresolved_content_findings:0,verdict:'pass'},questions:rows,source_checks:sourceChecks,official_reading:official,learning_reading:learning,source_discrepancy_review:{learning:'고급연습 L6943의580-A10 표시는 현행A1(PDF604 L25363~25368)의 설명과 일치하며 실제A10(PDF606 L25448~25451)은 추가 진술 문맥이다.',verdict:'author_correction_confirmed',original_bytes_preserved:true},footnote_review:{pdf602:'각주2·3은210.6(b)(i)/(iii)의 경영진 감사전제 책임을 연결한다. 이번 핵심 진술의 직접 명제는580.10·11본문 자체에 완결되어 있다.',pdf604:'각주4는705의견변형 기준서 연결이다.',pdf609:'각주7은A22의260.16(c)(ii),8은A25의230.8(c)/10으로16·17의 추가 배점으로 전용하지 않는다.',pdf610:'A26각주9=705.9. 실제PDF771의 증거부족·중요하고전반적 효과 조건과 대조했다.'},comparison_reading:comparison,source_file_hash_checks:sourceFiles,author_review_count:r.length,unresolved:[],limits:['실제 기출의 원시험 PDF는 이 peer가 확보·대조하지 않았다. 학습자료의 출제 표시·원발문·공통사실·해설을 직접 대조했다.','이 결과는 agent 독립 의미검수이며 사람 확인, 실제 Luna 채점, 정본·공개본·운영 DB 반영과 별개이다.']};
const outputPath=`${batch}/a-peer-review.json`;fs.writeFileSync(outputPath,JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify({file:outputPath,sha256:fileHash(outputPath),summary:output.summary},null,2));
