import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {CONTENT_CHECKS,EFFICIENT_RUNTIME_FILES,createEfficientReviewReceipt,createEfficientValidationContext,assertEfficientEvidenceUnchanged} from '../../../questionEfficientReview.ts';
import {reviewedContentHash} from '../../../questionReviewIdentity.ts';
import {validateAuthoringBank} from '../../../questionBankPublication.ts';
import {compileLearningCatalog} from '../../../../scripts/build-learning-unit-catalog.ts';
import {selectLearningQuestionSet,learningUnitId} from '../../../../lib/learningUnits.ts';
import {buildGradingPrompt,buildGradingResponseSchema,groundJudgment,applyQuestionSetJudgment} from '../../../../lib/questionV3Grading.ts';
import {contentHash} from '../../../../lib/learningSubmission.ts';
const D='cpa_uploader/drafts/standard-additional-2026-09-13',P=D+'/publication-v1';
const read=f=>JSON.parse(fs.readFileSync(f,'utf8')),sha=b=>createHash('sha256').update(b).digest('hex');
const ref=file=>({file,sha256:sha(fs.readFileSync(file))});
const write=(file,v)=>{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(v,null,2)+'\n',{flag:'wx'});return ref(file);};
const text=(file,v)=>{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,v,{flag:'wx'});return ref(file);};
assert(!fs.existsSync(P+'/batch.json'),'새 수락 증거를 덮어쓸 수 없음');
const canonical={authoring:'cpa_uploader/data/cpa_question_sets_v3.authoring.json',ledger:'cpa_uploader/data/cpa_question_sets_v3.promotions.json',public:'cpa_uploader/data/cpa_question_sets_v3.public.json',encrypted:'data/cpa_question_sets_v3.authoring.enc.json',catalog:'cpa_uploader/data/learning-question-classifications.json'};
const baseline=Object.entries(canonical).map(([name,file])=>{const copy=P+'/baseline/'+name+'.json';fs.mkdirSync(path.dirname(copy),{recursive:true});fs.copyFileSync(file,copy,fs.constants.COPYFILE_EXCL);return{name,...ref(file),backup:copy};});
write(P+'/baseline.json',baseline);
const original=read(canonical.authoring),oldCatalog=read(canonical.catalog),review=read(D+'/agent-review.json'),index=read(D+'/index.json');
assert.equal(ref(canonical.authoring).sha256,read(D+'/research.json').bank_sha256,'은행이 바뀌었으므로 중복 재검토 필요');
for(const g of read(D+'/grading/run-v1/manifest.json').inputs)assert.equal(ref(g.file).sha256,g.sha256,'과거 실행 입력 변경');
const additions=index.sets.map(s=>read(s.file));assert.equal(additions.length,6);assert.equal(additions.flatMap(s=>s.subquestions).length,13);
for(const s of additions)assert(!original.some(x=>x.id===s.id));
const bank=[...original,...additions];assert.deepEqual(validateAuthoringBank(bank).errors,[]);
const bankRef=write(P+'/evidence-bank.json',bank);
const entries=oldCatalog.classifications.map(c=>({set_id:c.source_set_id,subquestion_id:c.subquestion_id,question_style:c.question_style,topic_ids:c.topic_ids,standalone_prompt:c.standalone_prompt,case_fact_ids:c.case_fact_ids??[],reason:'내용이 동일한 기존 정본의 확인된 분류를 보존한다.'}));
for(const s of original)for(const c of oldCatalog.classifications.filter(c=>c.source_set_id===s.id))assert.equal(c.source_content_hash,contentHash(s));
for(const s of additions)for(const q of s.subquestions){const r=review.questions.find(r=>r.question===`${s.id}/${q.id}`);assert(r&&r.unresolved_items.length===0&&r.status==='content_reviewed');entries.push({set_id:s.id,subquestion_id:q.id,question_style:q.question_style,topic_ids:q.topic_ids,standalone_prompt:q.prompt,case_fact_ids:[],reason:r.style_reason+' '+r.topic_reason});}
const classificationReview=write(P+'/classification-review.json',{source_file:bankRef.file,source_file_sha256:bankRef.sha256,entries});
const compiled=compileLearningCatalog(bank,entries,oldCatalog.topics);
const catalogRef=write(P+'/evidence-catalog.json',{schema_version:1,source_file:bankRef.file,source_file_sha256:bankRef.sha256,review_file:classificationReview.file,review_file_sha256:classificationReview.sha256,topics:oldCatalog.topics,classifications:compiled.classifications});
const scope=write(P+'/scope.json',{targets:additions.map(s=>({set_id:s.id,subquestion_ids:s.subquestions.map(q=>q.id)}))});
const policy=write(P+'/policy.json',{scope,model:'gpt-5.6-luna',grading_point_tolerance:1,minimum_within_tolerance_ratio:.95,content_error_tolerance:0,statistical_confidence_claim:false,budget_usd:null,budget_enforcement:'not_specified',new_api_calls:0,original_model_responses_reprocessed:39,origin_manifest:ref(D+'/grading/run-v1/manifest.json')});
const qa=read(D+'/qa-representatives.json').cases;
const representatives=write(P+'/representatives.json',{origin:ref(D+'/qa-representatives.json'),cases:qa.map(c=>({...c,expected_points:c.expected_score,expected_verdicts:c.expected_criteria}))});
const files=[D+'/agent-review.json',D+'/source-boundary-review.json',D+'/discrepancy-analysis.json',D+'/verification-receipt.json',D+'/qa-representatives.json',D+'/research.json',D+'/comparison-inventory.json',D+'/sources/provenance.json',D+'/grading/run-v1/manifest.json',P+'/authorization.md',P+'/prepare.mjs'];
const agentReviews=additions.map(s=>({set_id:s.id,content_hash:reviewedContentHash(s),reviewer_id:'Codex authoring agent; same-thread evidence reuse',reviewed_at:review.review_date,method:'agent_content_review',human_review_performed:false,evidence:files.map(ref),questions:s.subquestions.map(q=>{const r=review.questions.find(r=>r.question===`${s.id}/${q.id}`);return{subquestion_id:q.id,criterion_ids:q.criteria.map(c=>c.id),source_ref_ids:[...new Set([...q.requirements.map(r=>r.source_ref_id),...q.criteria.flatMap(c=>c.source_ref_ids)])],checks:Object.fromEntries(CONTENT_CHECKS.map(c=>[c,'pass'])),rationale:r.point_rationale+' '+r.comparison.reason+' '+r.style_reason};}),unresolved_content_findings:[]}));
write(P+'/agent-reviews.json',agentReviews);
const jobs=qa.map(c=>{
 const source=additions.find(s=>s.id===c.set_id),unit=learningUnitId(source.id,'standard',c.subquestion_id);
 const meta=compiled.classifications.filter(m=>m.source_set_id===source.id&&m.subquestion_id===c.subquestion_id);
 const set=selectLearningQuestionSet(source,meta,unit),old=P.replace('/publication-v1','')+'/grading/run-v1/'+c.id;
 const oldInput=read(old+'.input.json');assert.deepEqual(oldInput.case,c);assert.deepEqual(oldInput.projected_set,set);assert.deepEqual(oldInput.answers,{[c.subquestion_id]:c.answer});
 const projected=write(P+'/projections/'+c.id+'.json',set),answers=oldInput.answers;
 const expected=[{subquestion_id:c.subquestion_id,expected_points:c.expected_score,expected_verdicts:c.expected_criteria}];
 const entry={id:c.id,source_set_id:source.id,learning_unit_id:unit,kind:c.role,projected_file:projected.file,projected_sha256:projected.sha256,evaluated_subquestion_ids:[c.subquestion_id],answers,expected_by_subquestion:expected,selection_evidence:[{...(c.role==='model'?bankRef:representatives),subquestion_id:c.subquestion_id,case_id:c.role==='model'?null:c.id,kind:c.role,reason:c.selection_reason}]};
 const prompt=buildGradingPrompt(set,answers),schema=buildGradingResponseSchema(set,answers),request=read(old+'.request-1.json'),wire=read(old+'.response-1.json'),traces=read(old+'.trace.json'),usage=read(old+'.usage.json');
 assert.equal(request.params.input,prompt);assert.deepEqual(request.params.text.format.schema,schema);
 const judgment=groundJudgment(traces.at(-1).response,set,answers),result=applyQuestionSetJudgment(set,answers,judgment);assert.deepEqual(result,read(old+'.result.json').result);
 const comparisons=result.subquestions.map(q=>{const e=expected.find(e=>e.subquestion_id===q.subquestion_id),delta=q.score-e.expected_points;return{subquestion_id:q.subquestion_id,evaluated:true,expected_points:e.expected_points,actual_points:q.score,delta,strict_matched:delta===0&&e.expected_verdicts.every(v=>q.criteria.find(k=>k.criterion_id===v.criterion_id).verdict===v.verdict),within_tolerance:Math.abs(delta)<=1};});
 const input=write(P+'/replayed/'+c.id+'.input.json',{entry,set,prompt,schema,model:'gpt-5.6-luna'});
 const transport=text(P+'/replayed/'+c.id+'.transport.jsonl',[{event:'request_started',sequence:1,params:request.params},{event:'response_received',response:wire.response,response_metadata:{request_id:wire.metadata.request_id}}].map(r=>JSON.stringify(r)).join('\n')+'\n');
 const trace=text(P+'/replayed/'+c.id+'.traces.jsonl',traces.map(t=>JSON.stringify(t)).join('\n')+'\n');
 const origin=['input','request-1','response-1','trace','usage','result'].map(suffix=>ref(old+'.'+suffix+'.json'));files.push(...origin.map(r=>r.file));
 return{entry,observation:{version:1,artifact_type:'efficient_grading_observation',transport:'model',response_injection:false,entry_id:c.id,model:'gpt-5.6-luna',source_set_id:source.id,learning_unit_id:unit,kind:c.role,projected_body_hash:contentHash(set),answers,original_expected:expected,prompt_sha256:sha(prompt),schema_hash:contentHash(schema),actual_sdk_calls:1,extra_quality_repeats:0,judgment,traces,result,files:{input,transport,traces:trace},security_findings:[],evaluated_subquestion_ids:[c.subquestion_id],strict_matched:comparisons.every(c=>c.strict_matched),within_tolerance:comparisons.every(c=>c.within_tolerance),subquestions:comparisons,usage:usage.map(provider=>({provider})),normalization:{new_api_calls:0,origin_files:origin,method:'Immutable earlier provider request/response reprocessed; no new execution or expected-value substitution'}}};
});
const snapshots=EFFICIENT_RUNTIME_FILES.map((file,i)=>{const copy=P+'/acceptance-runtime/'+i+'-'+path.basename(file)+'.snapshot';fs.mkdirSync(path.dirname(copy),{recursive:true});fs.copyFileSync(file,copy,fs.constants.COPYFILE_EXCL);return{...ref(copy),runtime_file:file};});
write(P+'/runtime-snapshots.json',snapshots);
const manifest=write(P+'/grading-manifest.json',{version:1,artifact_type:'efficient_grading_manifest',model:'gpt-5.6-luna',budget_usd:null,budget_enforcement:'not_specified',bank:bankRef,classifications:catalogRef,policy,inputs:[...new Set([...files,...additions.flatMap(s=>s.source_refs.map(r=>r.file)),...index.sets.flatMap(s=>[s.file,s.file.replace('.json','.authoring-plan.json')]),P+'/runtime-snapshots.json'])].map(ref),code_files:EFFICIENT_RUNTIME_FILES.map(ref),entries:jobs.map(j=>j.entry),normalization:{new_api_calls:0,original_model_responses_reprocessed:39,origin_manifest:ref(D+'/grading/run-v1/manifest.json'),runtime_note:'원 실행의 runtime·해시는 origin_manifest에 보존. 본 목록은 동일 요청의 새 수락·재처리 시점 runtime이다.'}});
const observations=jobs.map(j=>write(P+'/replayed/'+j.entry.id+'.observation.json',{...j.observation,manifest}));
const batch=write(P+'/batch.json',{version:1,artifact_type:'cost_controlled_review_batch',created_at:new Date().toISOString(),authorization:{evidence:ref(P+'/authorization.md'),agent_review_and_representative_grading:true,production_publication:true},grading_manifest:manifest,observations,agent_reviews:agentReviews,runtime_snapshots:snapshots,residual_grading_findings:[]});
const context=createEfficientValidationContext(),receipts=additions.map(s=>createEfficientReviewReceipt(batch,s,context));assertEfficientEvidenceUnchanged(context);
for(const r of baseline)assert.equal(ref(r.file).sha256,r.sha256,'준비 중 다른 작업 변경');
write(P+'/preparation-completion.json',{status:'evidence_reprocessed_and_validated',new_api_calls:0,reprocessed_model_responses:39,ids:additions.map(s=>s.id),counts:{sets:bank.length,questions:bank.flatMap(s=>s.subquestions).length,points:bank.flatMap(s=>s.subquestions).flatMap(q=>q.criteria).reduce((n,c)=>n+c.max_points,0)},receipts});
console.log(JSON.stringify({status:'ready',sets:additions.length,questions:13,reprocessed:39,new_api_calls:0}));
