import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {buildSourceCatalog} from '../../../questionSourceCatalog.mjs';
const D='cpa_uploader/drafts/case-applied-2026-09-14';
const R='cpa_uploader/analysis/reviews/case-applied-2026-09-14';
const read=f=>JSON.parse(fs.readFileSync(f));
const hash=f=>createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const write=(f,x)=>fs.writeFileSync(f,JSON.stringify(x,null,2)+'\n',{flag:'wx'});
fs.mkdirSync(D,{recursive:true});
const bank='cpa_uploader/data/cpa_question_sets_v3.authoring.json';
const catalog='cpa_uploader/data/learning-question-classifications.json';
const classification=read(catalog).review_file;
for(const [source,name]of [[bank,'bank-before.json'],[catalog,'catalog-before.json'],[classification,'classification-before.json']])fs.copyFileSync(source,D+'/'+name,fs.constants.COPYFILE_EXCL);
const sourceCatalog=buildSourceCatalog();write(D+'/source-catalog.json',sourceCatalog);
const b=read(bank),c=read(catalog);assert.equal(c.source_file_sha256,hash(bank));
const caseIds=[...new Set(c.classifications.filter(c=>c.question_style==='case').map(c=>c.source_set_id))];
write(R+'/baseline.json',{created_at:new Date().toISOString(),bank:{file:bank,sha256:hash(bank)},catalog:{file:catalog,sha256:hash(catalog)},classification:{file:classification,sha256:hash(classification)},sets:b.length,questions:b.flatMap(s=>s.subquestions).length,case_sets:caseIds.length,case_questions:c.classifications.filter(c=>c.question_style==='case').length,case_ids:caseIds});
write(R+'/policy-input.json',{budget_usd:null,budget_enforcement:'not_specified',note:'이번 추가 배치의 금액 상한은 별도 지정되지 않았다. 기존 모델 Luna와 제공자 측 한도 오류 중단 정책을 유지하며 미확인 한도 금액을 추정하지 않는다.'});
console.log({sets:b.length,questions:b.flatMap(s=>s.subquestions).length,case_sets:caseIds.length,source_units:sourceCatalog.units.length});
