import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const directory=path.dirname(fileURLToPath(import.meta.url));
const control='cpa_uploader/analysis/reviews/delegated-authoring-2026-09-11';
const manifestFile=control+'/final-153-v3/manifest.json';
const read=f=>JSON.parse(fs.readFileSync(f,'utf8'));
const sha=f=>createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const entry=read(manifestFile).entries.find(e=>e.plan_id==='T14-A'),original=read(entry.qa_file),question=read(entry.file);
if(sha(entry.file)!==entry.sha256||sha(entry.qa_file)!==entry.qa_sha256)throw Error('Original input changed');
const proposal=structuredClone(original),target=proposal.cases.find(c=>c.id==='sub1/omit-sentence-1'),before=structuredClone(target);
target.expected_points=1;
const verdict=target.expected_verdicts.find(v=>v.criterion_id==='sub1.crit1');
verdict.verdict='not_met';
verdict.reason='그룹감사인의 일반적인 증거 입수 책임만 제시했다. 독립성 미충족 A에 대한 비의존 또는 직접 수행을 명시하거나 필연적으로 함축하지 않아 업무 요청 불가 판단은 누락이다.';
target.note='600.20/A39, 발문, criterion scope의 전체 문맥을 총괄과 독립 대조하여 원 기대2를1로 정정했다. 원답안은 바꾸지 않았으며 A 비의존·그룹팀 직접 수행을 명시한 양성대조는2점을 유지한다. 원QA와 이전실측은 보존한다.';
const positive=proposal.cases.find(c=>c.id==='sub1/implicit-judgment');
if(positive.expected_points!==2||!positive.answer.includes('A에게 의존하지 않고')||!positive.answer.includes('직접'))throw Error('Positive control mismatch');
if(proposal.cases.some((c,i)=>c.answer!==original.cases[i].answer))throw Error('Any answer changed');
if(proposal.cases.filter(c=>c.id!==target.id).some(c=>JSON.stringify(c)!==JSON.stringify(original.cases.find(o=>o.id===c.id))))throw Error('Unrelated QA changed');
const qaFile=path.join(directory,'qa-cases-t14-a-v2.json');fs.writeFileSync(qaFile,JSON.stringify(proposal,null,2)+'\n',{flag:'wx'});
const sources=question.source_refs.filter(s=>['std-A39','std-20'].includes(s.id)).map(s=>({...s,file_sha256:sha(s.file),quote_present:fs.readFileSync(s.file,'utf8').includes(s.source_quote)}));
if(sources.some(s=>!s.quote_present))throw Error('Source quote absent');
const proof={recorded_at:new Date().toISOString(),status:'qa_expectation_followup_prepared_for_actual_recheck',api_calls:0,question:{file:entry.file,sha256:entry.sha256,changed:false},original_qa:{file:entry.qa_file,sha256:entry.qa_sha256},followup_qa:{file:qaFile,sha256:sha(qaFile)},manifest:{file:manifestFile,sha256:sha(manifestFile)},changed_case:{before,after:target,answer_preserved:before.answer===target.answer},unchanged_positive_control:positive,all_original_cases:original.cases.length,all_original_answers_preserved:true,only_one_case_expectation_changed:true,sources,criteria:question.subquestions.find(q=>q.id==='sub1').criteria,prior_evidence:'../../phase-two-v5/t14-a/author5b/failure-evidence.json',decision:'원 단문은 일반적 증거 입수 책임과 양립하므로 c1 not_met·c2 met·1점이다. 발문의 대안 요구만으로 비의존/직접 수행이라는 답안에 없는 결론을 보충하지 않는다. 명시적 비의존·직접 수행의 기존 양성대조는 두 요구를 함축하여2점이다. 정정은 답안이나 문항을 변경하지 않고 잘못된 작성자 기대만 고친다.',authorization:'총괄이 600.20/A39·실제 발문·criterion scope를 대조한 뒤 동일답안의 c1 met→not_met, 합계2→1 정정을 지시했다. 사람 검수로 표시하지 않는다.'};
fs.writeFileSync(path.join(directory,'lineage.json'),JSON.stringify(proof,null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({cases:original.cases.length,changed_expectation:target.id,before:before.expected_points,after:target.expected_points,positive:positive.expected_points,all_answers_preserved:true,api_calls:0}));
