import fs from 'node:fs';
import {sha256,jsonHash,reviewedContentHash} from '../../../questionReviewIdentity.ts';
import {validateQuestionSetV3} from '../../../../lib/questionV3.ts';
const D='cpa_uploader/drafts/case-applied-2026-09-14',B=`${D}/b`;
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const sets=read(`${B}/sets.json`),design=read(`${B}/design.json`),qa=read(`${B}/qa.json`);
const notes=[
 {facts:'유형 2 보고서의 실제 테스트기간 1~9월과 감사대상인 1~12월을 대조해야 10~12월 운영효과성의 증거 공백을 설명한다. 유형 명칭만으로 결정하지 않는다.',points:'연간 입증 제안에 대한 판단과 실제 기간 불일치의 이유를 각 1점으로 구별한다. 추가절차 목록·시스템 변경·테스트 예외를 이 물음에 숨겨 요구하지 않는다.',answer:'연간 통제증거로 충분하지 않다는 결론과 보고서가 잔여 3개월을 다루지 않는다는 이유가 KGA402.17(a)(c)·A32에 부합한다.',source:['KGA402.17(a)(c)','KGA402.A32'],nondup:'pilot-13-007은 유형1 보고서의 운영효과성 증거 부재이다. 신규는 이미 유형2인 보고서의 기간 불일치이며, pilot-13-011의 하위서비스 제외·보충통제도 별도 조건으로 제외한다.'},
 {facts:'10월 시스템 교체와 승인절차 변경 및 직접 자료접근 가능성이, 과거 증거를 재사용할 수 없는 이유와 잔여기간 테스트의 구체적 대상을 정한다.',points:'변경의 증거상 영향과 구체적인 통제테스트를 각 1점으로 구별한다. 변경 항목 3개의 전수 열거 또는 모든 추가증거 대안은 요구하지 않는다.',answer:'새 시스템 지급파일의 실제 승인 수행을 검사한다는 답은 KGA402.A33·A34의 변경 및 잔여기간 추가증거와 부합한다. 급여총액의 재계산만 제시한 오답은 승인통제 운영테스트가 아니다.',source:['KGA402.A32','KGA402.A33','KGA402.A34'],nondup:'pilot-13-011 exp1의 이용자기업 보충통제 담당자 변경과 달리 외부 서비스조직 시스템·승인통제 자체가 변경된 조건이다. pilot-13-007의 직접 통제테스트와 의도된 적용 심화가 있으나 추가증거의 이유가 다르다.'},
 {facts:'예외가 발견된 지급파일 승인절차가 다온의 급여에도 적용된다는 관련성이 필요하다. 실제 지급 오류에 대한 별도 검사결과가 없는 사실과 다른 통제 테스트 결과가 있는 사실을 평가하며, 지문이 전체 배제 여부의 결론을 대신 주지 않는다.',points:'전체 자동 배제 판단과 해당 예외의 관련성·증거 영향을 평가하는 행위를 각 1점으로 분리한다. 단순 예외 존재 반복이나 실제 부정 지급 확정에는 적용 점수를 주지 않는다.',answer:'A38은 예외·변형의견이 유형2 보고서의 자동 무용성을 뜻하지 않는다고 명시한다. 17(d)·A31에 따라 관련 통제테스트 결과가 회사 위험평가에 주는 증거를 평가하는 답이다.',source:['KGA402.17(d)','KGA402.A31','KGA402.A38'],nondup:'기존 유형2 사례의 하위서비스 제외 및 이용자기업 보충통제와 구별되는, 보고서 내부의 실제 승인 예외 평가 목표이다.'},
 {facts:'위탁상품 설명과 발송일 매출기록이 불일치하지만 계약·기말 판매상태를 아직 확인하지 않은 초기단계이다. 어느 정보가 틀렸는지 정하지 않고 관련 자료를 조사해야 한다.',points:'경영진 논의와 구체적 원인 조사절차를 각 1점으로 구별한다. 조사자료 전부의 기계적인 열거 또는 다음 단계의 의견은 요구하지 않는다.',answer:'720.16의 경영진 논의와 재무제표·기타정보의 오류 또는 이해 갱신 여부 확인을 실제 계약조건·판매내역 대조에 적용한다. 기타정보 삭제부터 지시하는 오답은 두 명제를 충족하지 않는다.',source:['KGA720.16'],nondup:'pilot-16-003의 일반 열람·수정요청 및 pilot-16-011의 기타정보 오류로 결론 난 후 수정거부와 달리 아직 오류 소재가 결정되지 않은 원인 조사이다.'},
 {facts:'후속 종결자료에서는 재무제표의 매출·매출채권 오류가 충분한 증거로 확인되고 미수정이며 중요하지만 특정 항목에 국한된다. 발견 경로와 오류 소재를 구별해야 한다.',points:'한정의견 판단과 그 의견을 뒷받침하는 실제 왜곡표시·비전반성의 이유를 각 1점으로 평가한다. 적정의견 유지가 잘못이라는 판단을 한정의견 선택과 중복 배점하지 않는다.',answer:'720.20은 재무제표 왜곡표시면 해당 기준서로 대응하도록 요구하고 705.7(a)는 중요하나 전반적이지 않은 확인된 왜곡표시에 한정의견을 요구한다. 기타정보 단락으로 적정의견을 유지할 수 없다.',source:['KGA720.20','KGA705.7(a)'],nondup:'pilot-16-011은 재무제표 자체 오류를 제외한 기타정보 수정거부이다. 새 물음은 오류가 재무제표에 있는 경우의 별도 보고처리이며 보고서일 후 경로는 제외한다.'},
 {facts:'가동중단에 관한 기타정보가 사실이라는 확인은 정상가동·지속판매를 전제로 한 감사인의 기존 재고 위험평가를 지지하지 않는다. 새로운 행정명령·생산기록을 재고 평가와 연결해야 한다.',points:'기업 이해와 위험평가의 수정이라는 행위 1점, 수정위험에 대응한 구체적 감사절차 1점이다. 성격·시기·범위 단어 각각이나 재고평가금액에 숨은 점수를 두지 않는다.',answer:'720.20·A51 및 315.37·A236의 새 정보에 따른 위험평가 수정과 330.6·A4~A8의 추가절차 설계·수행을 판매가능성·후속 판매자료에 적용한다.',source:['KGA720.20','KGA720.A51','KGA315.37','KGA315.A236','KGA330.6','KGA330.A4~A8'],nondup:'pilot-06-008은 고유위험요소 및 회사 위험평가절차의 누락·적합성이다. 신규는 사업보고서에서 알게 된 새 사실에 따라 감사인 자신의 위험평가와 추가절차를 수정하는 흐름이다.'},
 {facts:'전기는 재고평가 오류가 적절히 수정되고 충분한 증거가 있으며, 당기는 별개의 중요하지만 전반적이지 않은 충당부채 누락이 남아 있다. 같은 감사인이 두 기간 전체를 보고한다는 업무범위도 필요하다.',points:'현재 보고하는 2025년 적정의견과 2026년 한정의견을 각각 1점으로 구별한다. 발문에서 제외한 이유를 명칭 점수의 숨은 요건으로 요구하지 않으며 물음3의 전기 의견변경 사유와 중복하지 않는다.',answer:'700.16·705.7(a)에 따른 기간별 의견과 710.A9의 서로 다른 기간에 다른 의견을 표명할 수 있다는 지침이 일치한다. 과거 발행된 전기 보고서를 소급 삭제하는 답과 구별한다.',source:['KGA700.16','KGA705.7(a)','KGA710.A9','KGA710.16'],nondup:'pilot-16-010은 전임감사인과 당기감사인의 계약·보고범위 분리이고 pilot-16-008은 대응수치에 관한 당기의견 영향이다. 신규는 계속감사의 비교재무제표 두 기간 의견을 함께 적용한다.'},
 {facts:'두 기간이 재무제표에 표시될 뿐 아니라 동일 감사인이 전기 전체도 보고한다는 명시된 업무범위를 이용해 의견에서 언급할 기간을 결정한다.',points:'2025·2026 두 기간을 대상에 포함하는 조치 1점과 비교재무제표·실제 보고범위의 이유 1점이다. 두 연도를 각각 1점으로 늘리지 않고 의견 종류는 다시 요구하지 않는다.',answer:'710.15는 표시되는 각각의 기간과 의견이 표명되는 각각의 기간을 언급하게 한다. 710.A9의 비교재무제표 범위에 비추어 이 사례에서 전기를 생략할 수 없다.',source:['KGA710.15','KGA710.A9'],nondup:'pilot-16-010의 전임감사인 재발행 조건에서 당기만 보고하는 상황과 달리, 이 사례는 같은 감사인이 두 기간에 대해 보고할 계약이다.'},
 {facts:'동일 감사인의 과거 2025년 한정의견과 오류를 수정한 전기에 대한 이번 의견이 달라진다는 조건 및 실제 재고평가 수정 사유가 필요하다.',points:'기타사항문단에 차이를 다루는 보고조치 1점과 실제 전기 재고평가 오류의 수정·해소라는 설명 1점이다. 당기 소송충당부채 오류나 감사인 교체를 전기 의견변경 이유로 인정하지 않는다.',answer:'710.16은 해당 감사인의 전기 의견이 이전과 다른 경우 중요한 사유를 기타사항문단에 공시하도록 요구한다. A11의 전기 의견 변경 문맥도 확인했고 주석만으로 이를 생략할 수 없다는 답이 맞다.',source:['KGA710.16','KGA710.A11'],nondup:'2023 CPA 문제10 물음4④의 원발문·해설에 직접 대응하지만 실제 변경 사유를 사례에 적용하도록 확장한다. 다른 교재 재수록을 별도 기출로 더하지 않는다.'}
];
if(sets[0].shared_context.facts.some(f=>f.text.includes('모든 통제가 실패하였다고 결론')))throw new Error('Await revised factual wording');
const comparison=design[1].compared_existing_sets.find(x=>x.set_id==='pilot-06-008');
if(comparison.difference.includes('위험 재평가의 일반요건'))throw new Error('Await corrected comparison inventory');
let index=0;const reviews=[],staticErrors=[];
for(const s of sets){
 const errors=validateQuestionSetV3(s,{verifySourceQuotes:true,cwd:process.cwd()}).errors;
 staticErrors.push(...errors.map(e=>`${s.id}: ${e}`));
 const d=design.find(d=>d.set_id===s.id);
 for(const q of s.subquestions){
  const note=notes[index++],reps=qa.filter(x=>x.set_id===s.id&&x.subquestion_id===q.id);
  if(reps.length!==2||reps.some(r=>r.expected_points!==r.met_criterion_ids.length||r.met_criterion_ids.some(c=>!q.criteria.some(x=>x.id===c))||(r.kind==='partial'?r.expected_points!==1:r.expected_points!==0)))throw new Error(`QA identity ${s.id}/${q.id}`);
  const refs=[...new Set(q.criteria.flatMap(c=>c.source_ref_ids))];
  const sources=s.source_refs.filter(r=>refs.includes(r.id));
  reviews.push({set_id:s.id,subquestion_id:q.id,criterion_ids:q.criteria.map(c=>c.id),source_ref_ids:refs,reviewed_content_hash:reviewedContentHash(s),question_sha256:jsonHash({shared_context:s.shared_context,subquestion:q}),question_style:q.question_style,topic_ids:q.topic_ids,max_points:q.criteria.reduce((a,c)=>a+c.max_points,0),checks:Object.fromEntries(['source','answer','prompt','points','style','topics','edition','nonduplication'].map(k=>[k,'pass'])),rationale:note.answer+' '+note.points,check_rationales:{source:note.source.join(', ')+' 본문·조건·관련 적용자료를 실제 읽고 모든 requirement/criterion의 직접 및 보충 source_ref_ids와 대조했다.',answer:note.answer,prompt:'발문 요구와 모범답안의 명제·조건·제외 범위를 양방향으로 대조했다. '+note.points,points:note.points,style:note.facts,topics:'실제 적용 목표에 맞춘 '+q.topic_ids.join('·')+' 주제이다. 답안 형식 descriptive와 사례형 case를 혼동하지 않는다.',edition:'2026 공식 전문의 해당 본문과 시행일을 직접 읽어 등록 2025 인용과 내용 일치를 확인했다. 720은 2025년 말 자산 8천억원의 주권상장법인이라는 적용조건을 확인했다. source_ranges 참조.',nonduplication:note.nondup},source_paragraphs:note.source,source_ranges:d.official_current_edition_comparison.map(r=>({file:r.file,file_sha256:r.file_sha256,start_line:r.start_line,end_line:r.end_line,paragraphs:r.paragraphs})),source_quote_hashes:Object.fromEntries(sources.map(r=>[r.id,sha256(r.source_quote)])),qa_rationale:'저장 모범답안은 두 독립 criterion을 충족하여 2점이다. 대표 부분답안은 met_criterion_ids에 명시된 하나만 충족하여 1점이고 대표 오답은 두 의미를 반대로 처리하거나 필요한 조사를 부정하여 0점이다. 이는 내용 기대값 검토이며 실제 모델 채점은 별도이다.',qa_inputs:reps.map(r=>({kind:r.kind,answer_sha256:sha256(r.answer),expected_points:r.expected_points,met_criterion_ids:r.met_criterion_ids})),unresolved_content_findings:[]});
 }
}
if(staticErrors.length)throw new Error(staticErrors.join('\n'));
const files=[...new Set(sets.flatMap(s=>s.source_refs.map(r=>r.file)).concat(design.flatMap(d=>d.learning_source_reading.map(r=>r.file)),['cpa_uploader/drafts/frequency-gap-2026-09-10/sources/kga-2026-pymupdf-pages.txt',`${D}/bank-before.json`]))];
const out={version:'independent-agent-content-review-v1',reviewer_id:'agent:/root/next_cases_early',method:'independent_agent_manual_content_review',human_review_performed:false,paid_api_semantic_review_performed:false,actual_model_grading:'not_performed_by_this_reviewer; parent retains separate Luna evidence',reviewed_at:new Date().toISOString(),status:'pass',file_bindings:Object.fromEntries(['sets','design','review','qa'].map(k=>[k,{file:`${B}/${k}.json`,sha256:sha256(fs.readFileSync(`${B}/${k}.json`))}])),scope:{case_count:sets.length,subquestion_count:reviews.length,qa_count:qa.length,all_questions_fact_dependent:true,fact_character_counts:sets.map(s=>({set_id:s.id,characters:Array.from(s.shared_context.facts.map(f=>f.text).join('\n')).length,method:'LF join, Unicode codepoints including spaces'}))},resolved_findings:[{id:'B13-FACT-HINT-01',set_id:sets[0].id,subquestion_id:'sub3',finding:'모든 통제 실패를 결론 내릴 수 없다는 판단 방향이 부모에 명시되어 있었음',resolution:'실제 다른 통제 테스트 결과의 존재와 다온 급여 오류에 대한 별도 검사결과 부재라는 사실로 바뀐 최종 부모를 직접 확인함. 정답·배점은 유지됨.'},{id:'B16-COMPARISON-01',set_id:sets[1].id,subquestion_id:'sub3',finding:'비교장부가 pilot-06-008을 위험 재평가 일반요건으로 설명했지만 실제 현행 물음은 고유위험요소 및 회사 위험평가절차의 누락 검토였음',resolution:comparison.difference}],question_reviews:reviews,source_file_bindings:files.map(file=>({file,sha256:sha256(fs.readFileSync(file))})),static_checks:{shape_and_exact_quotes:'pass',qa_ids_and_role_points:'pass',no_model_calls:true},unresolved_content_findings:[]};
fs.writeFileSync(`${D}/b-peer-review.json`,JSON.stringify(out,null,2)+'\n');
console.log(JSON.stringify({status:out.status,file:`${D}/b-peer-review.json`,sha256:sha256(fs.readFileSync(`${D}/b-peer-review.json`)),file_bindings:out.file_bindings,questions:reviews.length}));
