// Preserve the user-requested stop boundary; no API calls.
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {jsonHash} from '../../../../../cpa_uploader/questionReviewIdentity.ts';
const dir=path.dirname(fileURLToPath(import.meta.url)),root='cpa_uploader/drafts/delegated-authoring-2026-09-11';
const read=(f:string)=>JSON.parse(fs.readFileSync(f,'utf8')),sha=(f:string)=>createHash('sha256').update(fs.readFileSync(f)).digest('hex'),ref=(file:string)=>({file,sha256:sha(file)});
const partial=path.join(root,'n04/phase-two-v5/t13-a/generated-bank-v3-refill02-01'),inputFile=path.join(partial,'inputs.json'),inputs=read(inputFile),semantic=read(inputs.semantic_file).reviews[0],set=read(path.join(root,'n04/pilot-13-009.json'));
const logFile=path.join(partial,'initial.grading.jsonl'),events=fs.readFileSync(logFile,'utf8').trim().split(/\r?\n/).filter(Boolean).map(line=>JSON.parse(line));
const plans=new Map<string,any>();
for(const sample of semantic.cases){const q=set.subquestions.find((q:any)=>q.criteria.some((c:any)=>sample.unit_id===`criterion:${q.id}:${c.id}`));if(!q)throw Error('Unknown target');const answers=Object.fromEntries(set.subquestions.map((s:any)=>[s.id,s.id===q.id?sample.answer:''])),id=jsonHash(answers);const p=plans.get(id)||{id,answers,source_cases:[]};p.source_cases.push({unit_id:sample.unit_id,kind:sample.kind,expected:sample.expected});plans.set(id,p);}
plans.set('empty-answer',{id:'empty-answer',answers:Object.fromEntries(set.subquestions.map((q:any)=>[q.id,''])),source_cases:[]});
const completed=events.filter(e=>e.status==='completed'),completedIds=new Set(completed.map(e=>e.id)),remaining=[...plans.values()].filter(p=>!completedIds.has(p.id));
if(completedIds.size!==52||plans.size!==80)throw Error('Changed stop boundary; inspect before recording');
const six=['T04-A','T09-A','T09-B','T10-A','T12-A','T12-B'].map(id=>{const file=path.join(dir,id.toLowerCase(),'generated-bank-v3-refill02-01/summary.json');return{plan_id:id,...ref(file),summary:read(file)};});
const record={recorded_at:new Date().toISOString(),api_calls_by_script:0,reason:'사용자 최신 지시: 일단 API 채점은 멈추고 배점 정책을 고려한다.',stop_confirmation:{coordinator_reported_utc:'2026-09-11T05:17:32Z',coordinator_terminated_pids:[9600,9364],coordinator_api_node_process_count:0,own_exec_session:13308,own_session_exit_code:1,new_api_started_after_stop:false,time_provenance:'중지 UTC/PID/프로세스수는 총괄의 전달 기록. 직접 세션 종료도 확인했다. 응답없는 API의 서버 중지 시각을 추정하지 않는다.'},completed_author:{sets:16,unique_cases:746,valid_observations:800,live_model:760,production_blank:40,failed_transport:1,approved_extra_control_observations:12,source:ref(path.join(dir,'author-progress-016-complete-original-qa.json'))},completed_current_bank_v3_generated:{sets:6,initial_cases:six.reduce((n,r)=>n+r.summary.initial_cases,0),valid_observations:six.reduce((n,r)=>n+r.summary.recorded_executions,0),model_grader_observations:six.reduce((n,r)=>n+r.summary.nonempty_grader_executions,0),blank_observations:six.reduce((n,r)=>n+r.summary.blank_production_executions,0),records:six},interrupted_t13_a:{inputs:ref(inputFile),semantic:ref(inputs.semantic_file),raw_log:ref(logFile),semantic_cases:95,planned_initial_answers:plans.size,valid_completed_observations:completed.length,model_observations:completed.filter(e=>Object.values(e.answers).some((a:any)=>a.trim())).length,blank_observations:completed.filter(e=>Object.values(e.answers).every((a:any)=>!a.trim())).length,observed_mismatches:completed.filter(e=>!e.matched).map(e=>({id:e.id,answers:e.answers,expected:e.expected,actual:e.judgment,observations:1,additional_two_repeats_pending:true})),last_observed_case_id:completed.at(-1)?.id,next_unobserved_case_id:remaining[0]?.id,remaining_initial_cases:remaining,repeat_stage_started:fs.existsSync(path.join(partial,'repeat.grading.jsonl')),completion_summary_present:fs.existsSync(path.join(partial,'summary.json')),unobserved_request_policy:'다음 미관측 사례가 송신되었는지 또는 서버 응답을 냈는지는 이 완료로그만으로 확정할 수 없다. 유효 관측으로 세지 않고 재개 시 원 입력과 현재 코드 동일성부터 확인한다.'},not_started:{t14_a_new_generated:true,t11_a_exact_unit_diagnostics:4,t11_b_followup_plan_semantic_all_units:true},historical_bank_v2_generated:{valid_observations:120,not_added_to_current_bank_v3:true},all_original_logs_preserved:true,question_plan_score_or_canonical_modified_by_stop_record:false};
fs.writeFileSync(path.join(dir,'user-stop-2026-09-11-051732.json'),JSON.stringify(record,null,2)+'\n',{flag:'wx'});
fs.writeFileSync(path.join(dir,'pause-generated-bank-v3-after-refill.json'),JSON.stringify({reason:record.reason,coordinator_reported_utc:'2026-09-11T05:17:32Z',new_api_allowed:false},null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({file:path.join(dir,'user-stop-2026-09-11-051732.json'),sha256:sha(path.join(dir,'user-stop-2026-09-11-051732.json')),completed_generated:record.completed_current_bank_v3_generated.valid_observations,partial_t13a:completed.length,remaining_initial:remaining.length,active_processes:0}));
