import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {prepareSemanticReview,completeSemanticReview,createManualReviewTemplate,validateRecordedSemanticReview,validateSemanticReviewReceipt} from '../../../../questionSemanticReview.ts';
import {validatePromotionLedger} from '../../../../questionBankPublication.ts';
import {jsonHash} from '../../../../questionReviewIdentity.ts';
import {offlineReviewResult} from '../../../../../tests/helpers/questionSemanticReviewFixture.ts';

const b='cpa_uploader/analysis/reviews/point-review-and-publication-2026-09-11';
const read=(f:string)=>JSON.parse(fs.readFileSync(f,'utf8'));
const hash=(f:string)=>createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const inputs=['cpa_uploader/questionSemanticReview.ts',b+'/canonical-before.json','cpa_uploader/data/cpa_question_sets_v3.promotions.json'].map(file=>({file,sha256:hash(file)}));
const bank=read(b+'/canonical-before.json'),ledger=read('cpa_uploader/data/cpa_question_sets_v3.promotions.json');
const s=bank.find((s:any)=>s.id==='pilot-09-008');
const receipt=ledger.entries.filter((e:any)=>e.set_id===s.id&&e.to_status==='verified').at(-1).semantic_review;
function rehash(r:any){const body={...r};delete body.receipt_hash;r.receipt_hash=jsonHash(body);return r;}
const legacyErrors=validateRecordedSemanticReview(receipt,s);
const marked=structuredClone(receipt);marked.execution.source_coverage='requirements_and_criteria_v1';rehash(marked);
const markedMissingErrors=validateRecordedSemanticReview(marked,s);
const newAcceptanceErrors=validateSemanticReviewReceipt(receipt,s,{bank,maxInputChars:500000});
const markerWithoutRehash=structuredClone(receipt);markerWithoutRehash.execution.source_coverage='requirements_and_criteria_v1';
const markerHashErrors=validateRecordedSemanticReview(markerWithoutRehash,s);
const criterionMissing=structuredClone(receipt);
const cunit=criterionMissing.units.find((u:any)=>u.id.startsWith('criterion:sub2:')&&u.source_quotes.some((q:any)=>q.source_ref_id==='src50515head'));
if(!cunit)throw new Error('actual supplementary criterion source missing from baseline receipt');
cunit.source_quotes=cunit.source_quotes.filter((q:any)=>q.source_ref_id!=='src50515head');rehash(criterionMissing);
const criterionMissingErrors=validateRecordedSemanticReview(criterionMissing,s);
const sourceHashChanged=structuredClone(receipt);sourceHashChanged.source_files[0].sha256='0'.repeat(64);rehash(sourceHashChanged);
const sourceHashErrors=validateRecordedSemanticReview(sourceHashChanged,s);
const sourceMetadataChanged=structuredClone(receipt);sourceMetadataChanged.context.source_metadata[0].note+=' synthetic change';sourceMetadataChanged.context_hash=jsonHash(sourceMetadataChanged.context);rehash(sourceMetadataChanged);
const sourceMetadataErrors=validateRecordedSemanticReview(sourceMetadataChanged,s);
const prepared=prepareSemanticReview(s,{bank:[],authoringPlan:receipt.context.authoring_plan,packet:receipt.context.source_packet,maxInputChars:500000});
const newReceipt=completeSemanticReview(prepared,offlineReviewResult(prepared),{method:'manual_reasoned',model:null,performed_at:'2026-09-11T00:00:00Z',description:'isolated synthetic fixture; no actual semantic approval'});
const template=createManualReviewTemplate(prepared);
const changed=new Set(read(b+'/prepared-reviewed-v1/summary.json').canonical.changed_sets);
const allLedgerErrors=validatePromotionLedger(bank,ledger,true);
const unchangedLedgerErrors=validatePromotionLedger(bank.filter((s:any)=>!changed.has(s.id)),ledger,true);
const assertions={legacy_read_restored:legacyErrors.length===0,marked_missing_source_rejected:markedMissingErrors.some(e=>e.includes('src50515head')),new_acceptance_still_requires_union:newAcceptanceErrors.some(e=>e.includes('src50515head')),marker_is_receipt_hash_bound:markerHashErrors.some(e=>e.includes('해시')),legacy_criterion_source_still_required:criterionMissingErrors.some(e=>e.includes(cunit.id)&&e.includes('src50515head')),legacy_source_hash_still_bound:sourceHashErrors.some(e=>e.includes('source 파일이 변경')),legacy_source_metadata_still_bound:sourceMetadataErrors.some(e=>e.includes('metadata가 변경')),new_completion_marked:newReceipt.execution.source_coverage==='requirements_and_criteria_v1',new_template_marked:template.execution.source_coverage==='requirements_and_criteria_v1',all_original_ledger_pass:allLedgerErrors.length===0,unchanged_34_ledger_pass:unchangedLedgerErrors.length===0};
const report={version:1,method:'read-only actual historical receipt replay plus synthetic in-memory marker/source tampering probes; no prior receipt bytes or hashes altered',api_calls:0,core_or_bank_or_ledger_writes:0,input_files:inputs,input_files_unchanged:inputs.every(f=>hash(f.file)===f.sha256),original_receipt_hash:receipt.receipt_hash,assertions,errors:{legacy:legacyErrors,marked_missing:markedMissingErrors,new_acceptance:newAcceptanceErrors,marker_without_rehash:markerHashErrors,legacy_criterion_missing:criterionMissingErrors,source_hash_changed:sourceHashErrors,source_metadata_changed:sourceMetadataErrors,all_ledger:allLedgerErrors,unchanged_ledger:unchangedLedgerErrors}};
fs.writeFileSync(b+'/c/semantic-clarification-marker-followup-evidence.json',JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({assertions,failed:Object.entries(assertions).filter(([,pass])=>!pass),core_sha256:inputs[0].sha256},null,2));
if(Object.values(assertions).some(v=>!v))process.exitCode=1;
