import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const out=path.dirname(fileURLToPath(import.meta.url));
const D='cpa_uploader/analysis/reviews/point-review-and-publication-2026-09-11';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const read=f=>JSON.parse(fs.readFileSync(f,'utf8'));
const evidence=new Map();
const record=f=>{const b=fs.readFileSync(f);evidence.set(f,{file:f,sha256:sha(b),bytes:b.length});return JSON.parse(b.toString('utf8'));};
const walk=p=>fs.existsSync(p)?fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(p,e.name)):[path.join(p,e.name).replaceAll('\\','/')]):[];
const jsonl=f=>fs.readFileSync(f,'utf8').split(/\r?\n/).filter(Boolean).map(JSON.parse);
const m=record(D+'/execution-all-v6/manifest.json');
const pre=record(m.preflight_file), bank=record(m.bank_file), summary=record(D+'/prepared-reviewed-v6/summary.json');
const selected=bank.filter(s=>m.jobs.some(j=>j.set_id===s.id));
const count=sets=>({sets:sets.length,questions:sets.flatMap(s=>s.subquestions).length,criteria:sets.flatMap(s=>s.subquestions).flatMap(q=>q.scoring_criteria||q.criteria||[]).length});
const bankCriteria=sets=>sets.flatMap(s=>s.subquestions).flatMap(q=>q.rubric?.criteria||q.criteria||[]).length;
const actualCounts=count(selected);actualCounts.criteria=bankCriteria(selected);actualCounts.semantic_units=actualCounts.questions+actualCounts.criteria;
const qa=record(D+'/qa-prepared-v4/manifest.json');
const smoke=record(D+'/a/learning-unit-smoke-v3/manifest.json');
const smokeCheck=record(D+'/a/learning-unit-smoke-v3/local-validation.json');
const v6Stop=record(D+'/execution-canary-v6/semantic-a/summary.json');
const v6Files=[...walk(D+'/execution-canary-v6'),...walk(D+'/execution-remaining-v6'),...walk(D+'/execution-all-v6')];
const history=[];
const partials=[];
for(const dir of fs.readdirSync(D,{withFileTypes:true}).filter(e=>e.isDirectory()&&/^execution-/.test(e.name)).map(e=>e.name)){
  const files=walk(D+'/'+dir);
  for(const f of files.filter(f=>/\/(semantic|grading)\.json$/.test(f))){
    const r=record(f).reviews?.[0]; if(!r)continue;
    const sibling=f.replace(/\/(semantic|grading)\.json$/,'/summary.json');
    const s=fs.existsSync(sibling)?record(sibling):null;
    const chunk=f+'.chunks.jsonl';
    const grade=f+'.grading.jsonl';
    const traces=fs.existsSync(chunk)?jsonl(chunk):[];
    const grades=fs.existsSync(grade)?jsonl(grade):[];
    if(fs.existsSync(chunk))evidence.set(chunk,{file:chunk,sha256:sha(fs.readFileSync(chunk)),bytes:fs.statSync(chunk).size});
    if(fs.existsSync(grade))evidence.set(grade,{file:grade,sha256:sha(fs.readFileSync(grade)),bytes:fs.statSync(grade).size});
    history.push({directory:dir,file:f,set_id:r.set_id,kind:f.endsWith('/grading.json')?'grading_receipt':'semantic_receipt',verdict:r.verdict,units:r.units.length,all_unit_checks_pass:r.units.every(u=>Object.values(u.checks).every(v=>v==='pass')),cases:r.cases.length,execution:r.execution,source_files:r.source_files,content_hash:r.content_hash,bank_hash:r.bank_hash,context_hash:r.context_hash,receipt_hash:r.receipt_hash,summary_outcome:s?.outcome??null,summary_receipt_byte_hash_matches:s?.receipt_sha256===sha(fs.readFileSync(f)),grading_status:r.grading.status,grading_transport:r.grading.transport,runs:r.grading.runs.length,matched_runs:r.grading.runs.filter(x=>x.matched).length,empty_runs:r.grading.runs.filter(x=>!Object.values(x.answers).some(a=>String(a).trim())).length,semantic_chunk_records:traces.length,semantic_chunk_unique_units:new Set(traces.map(t=>t.unit_id)).size,semantic_chunk_transports:[...new Set(traces.map(t=>t.transport))],grading_jsonl_records:grades.length,grading_trace_responses:grades.flatMap(g=>g.trace||[]).filter(t=>t.response).length,grading_trace_stages:[...new Set(grades.flatMap(g=>g.trace||[]).map(t=>t.stage))],current_v6_reuse_approved:false});
  }
  for(const f of files.filter(f=>f.endsWith('.chunks.jsonl')&&!fs.existsSync(f.slice(0,-'.chunks.jsonl'.length))))partials.push({directory:dir,file:f,chunk_records:jsonl(f).length,status:'partial_chunks_without_final_receipt; not completed semantic review'});
}
const canary=history.filter(x=>x.directory==='execution-canary-v2'&&x.kind==='semantic_receipt');
const grading=history.find(x=>x.directory==='execution-canary-v2'&&x.kind==='grading_receipt');
const oldPasses=history.filter(x=>x.directory!=='execution-canary-v2'&&x.kind==='semantic_receipt'&&x.verdict==='pass');
const collection=record('cpa_uploader/raw/collections/2026-09-11-initial/manifest.json');
const collectionCheck=record(D+'/c/raw-source-inventory-v1/collection-followup.json');
const canonicalPath='cpa_uploader/data/cpa_question_sets_v3.authoring.json';
const originalPath=D+'/canonical-before.json';
const canonicalNow=record(canonicalPath), canonicalBefore=record(originalPath);
const canonicalDiffs=[];
function diff(a,b,p){if(JSON.stringify(a)===JSON.stringify(b))return;if(!a||!b||typeof a!=='object'||typeof b!=='object'){canonicalDiffs.push({path:p,before:a,after:b});return;}for(const k of new Set([...Object.keys(a),...Object.keys(b)]))diff(a[k],b[k],p+'/'+k);}
for(const s of canonicalBefore)diff(s,canonicalNow.find(x=>x.id===s.id),s.id);
const currentInputs=new Map();
for(const f of [...m.code_files,...m.jobs.flatMap(j=>[{file:j.file,sha256:j.sha256},{file:j.plan_file,sha256:j.plan_sha256},{file:j.qa_file,sha256:j.qa_sha256},...j.source_files])])if(f.file)currentInputs.set(f.file,f.sha256);
const inputMismatches=[];for(const [file,expected]of currentInputs){if(!fs.existsSync(file))inputMismatches.push({file,reason:'missing'});else{const actual=sha(fs.readFileSync(file));if(actual!==expected)inputMismatches.push({file,expected,actual});}}
const assertions=[];
const assert=(name,pass,detail)=>assertions.push({name,pass,detail});
assert('v6 bank file hash matches manifest',sha(fs.readFileSync(m.bank_file))===m.bank_sha256);
assert('selected set count',actualCounts.sets===119,actualCounts);
assert('selected subquestions',actualCounts.questions===280,actualCounts.questions);
assert('selected criteria',actualCounts.criteria===1113,actualCounts.criteria);
assert('semantic units',actualCounts.semantic_units===1393,actualCounts.semantic_units);
assert('v6 preflight',pre.errors.length===0&&pre.checked_sets===119, {api_calls:pre.api_calls,max_chunk:pre.largest_chunk_chars});
assert('QA prepared count',qa.unique_cases===6029&&qa.entries.reduce((n,x)=>n+x.cases,0)===6029,{manifest:qa.unique_cases,entries:qa.entries.reduce((n,x)=>n+x.cases,0)});
assert('learning smoke split',smoke.entries.length===249&&smoke.entries.every(e=>e.empty_execution==='passed_without_model'&&e.stored_answer_model_execution==='not_run'));
assert('canary v2 three pass semantic receipts',canary.length===3&&canary.every(x=>x.verdict==='pass'&&x.all_unit_checks_pass&&x.execution.transport==='model'));
assert('canary v2 35 raw semantic units',canary.reduce((n,x)=>n+x.units,0)===35&&canary.reduce((n,x)=>n+x.semantic_chunk_records,0)===35);
assert('grading19 all matched',grading.runs===19&&grading.matched_runs===19&&grading.grading_jsonl_records===19&&grading.grading_transport==='model');
assert('grading18 responses plus one empty',grading.grading_trace_responses===18&&grading.empty_runs===1);
assert('v6 stopped before new unit',v6Stop.gracefully_stopped&&v6Stop.recorded_sets===0&&v6Stop.results.length===0&&!v6Files.some(f=>/\/(semantic|grading)\.json$|\.chunks\.jsonl$|\.grading\.jsonl$/.test(f)));
assert('raw complete',collection.entries.length===471&&new Set(collection.entries.map(x=>x.sha256)).size===458&&collectionCheck.errors.length===0);
assert('canonical candidate content not applied; only documentation notes differ',canonicalNow.length===canonicalBefore.length&&canonicalDiffs.every(d=>/\/verification\/notes\/\d+$/.test(d.path)),{byte_equality:false,differing_note_strings:canonicalDiffs.length,current_counts:count(canonicalNow)});
assert('frozen input files match current bytes',inputMismatches.length===0,{files:currentInputs.size,mismatches:inputMismatches});
const result={version:1,checked_at:new Date().toISOString(),scope:'point-review-and-publication-2026-09-11 current v6 and direct predecessor execution receipts only; older delegated-authoring runs retain their own ledgers',api_calls:0,current:{bank_file:m.bank_file,bank_sha256:m.bank_sha256,full_bank_counts:{...count(bank),criteria:bankCriteria(bank)},selected_counts:actualCounts,manifest_file:D+'/execution-all-v6/manifest.json',manifest_sha256:sha(fs.readFileSync(D+'/execution-all-v6/manifest.json')),model:m.model,review_model:m.review_model,source_catalog_fingerprint:m.source_catalog_fingerprint,preflight:{errors:pre.errors,api_calls:pre.api_calls,largest_chunk_chars:pre.largest_chunk_chars,max_input_chars:pre.max_input_chars},summary_validation:summary.validation,qa:{unique_cases:qa.unique_cases,checked_cases:qa.checked_cases,deduplicated_aliases:qa.deduplicated_aliases,status:qa.status,execution:qa.execution,api_calls:qa.api_calls,errors:qa.errors},learning_smoke:{counts:smoke.counts,status:smoke.status,queue:smoke.nonempty_execution_queue,local_checks:smokeCheck.checks},v6_execution:{gracefully_stopped:v6Stop.gracefully_stopped,recorded_sets:v6Stop.recorded_sets,not_started_set_ids:v6Stop.not_started_set_ids,results:v6Stop.results,actual_calls_observed:0,receipt_or_raw_model_output_files:v6Files.filter(f=>/\/(semantic|grading)\.json$|\.chunks\.jsonl$|\.grading\.jsonl$/.test(f))}},canary_v2:{semantic_sets:canary.length,semantic_units:canary.reduce((n,x)=>n+x.units,0),semantic_chunk_records:canary.reduce((n,x)=>n+x.semantic_chunk_records,0),receipts:canary,grading},other_historical_pass_receipts:{count:oldPasses.length,units:oldPasses.reduce((n,x)=>n+x.units,0),entries:oldPasses,interpretation:'3 canary pass sets are not all historical successes. These older receipts are not accepted evidence for v6.'},all_history_receipts:history,partial_without_receipt:partials,raw:{original_paths:collection.entries.length,unique_files:new Set(collection.entries.map(x=>x.sha256)).size,unique_bytes:collectionCheck.unique_material_bytes,check_file:D+'/c/raw-source-inventory-v1/collection-followup.json'},unperformed:{current_v6_formal_semantic:true,current_v6_author_qa_model_grading:true,current_v6_nonempty_learning_smoke:true,current_v6_acceptance_and_publication:true,current_candidate_db_apply:true},remote_db_verification:'not queried; current candidate summary states no DB application, and local canonical remains before-candidate bytes',assertions,errors:assertions.filter(a=>!a.pass),evidence:[...evidence.values()]};
fs.mkdirSync(out,{recursive:true});
result.canonical_preservation={before_file:originalPath,current_file:canonicalPath,before_sha256:sha(fs.readFileSync(originalPath)),current_sha256:sha(fs.readFileSync(canonicalPath)),byte_equality:sha(fs.readFileSync(canonicalPath))===sha(fs.readFileSync(originalPath)),differences:canonicalDiffs,interpretation:'verification.notes의 문서 경로 후속으로 bytes가 다르다. 발문·정답·criterion·배점·기타 구조가 같으므로 이번 수정후보153세트의 내용이 정본에 반영됐다는 뜻이 아니다.'};
result.current_input_verification={files:currentInputs.size,mismatches:inputMismatches};
result.remote_db_verification='Remote DB was not queried. Candidate summary records no DB application; current local canonical remains 104/212/574 with documentation-note path updates only.';
const existing=path.join(out,'evidence.json'); const preserved=path.join(out,'evidence.initial-byte-assumption.json');if(fs.existsSync(existing)&&!fs.existsSync(preserved))fs.copyFileSync(existing,preserved);
fs.writeFileSync(existing,JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify({selected_counts:actualCounts,canary:result.canary_v2.semantic_units,grading:{runs:grading.runs,raw_responses:grading.grading_trace_responses,empty:grading.empty_runs},old_passes:result.other_historical_pass_receipts.count,old_pass_units:result.other_historical_pass_receipts.units,partial_count:partials.length,assertions:assertions.length,errors:result.errors},null,2));
