import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const base=path.dirname(fileURLToPath(import.meta.url)),read=file=>JSON.parse(fs.readFileSync(file,'utf8'));
const sha=file=>createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const control='cpa_uploader/analysis/reviews/delegated-authoring-2026-09-11',manifestFile=control+'/final-153-v1/manifest.json';
const entry=read(manifestFile).entries.find(entry=>entry.plan_id==='T12-A');
if(sha(entry.file)!==entry.sha256||sha(entry.qa_file)!==entry.qa_sha256)throw Error('Predecessor changed');
const original=read(entry.file),followup=structuredClone(original),set=Array.isArray(followup)?followup[0]:followup;
const criterion=set.subquestions.find(sub=>sub.id==='q2').criteria.find(criterion=>criterion.id==='q2.c1');
const previousCriterion=structuredClone(criterion);
const interpretation='최초 일자 후 절차의 한정 범위를 알리는 추가 일자 기재는 두 일자의 병존을 함축하므로 이 보존 명제를 충족한 것으로 인정한다. 최초 일자의 보존만 서술해도 충족하며 추가 일자의 범위 설명은 별도 필수요건이 아니다. 최초 일자의 삭제 또는 새 일자로 대체를 명시하면 충족하지 않는다.';
criterion.claim='추가 일자 방식에서는 최초 감사보고서일을 변경하지 않고 유지한다. '+interpretation;
criterion.critical_facts.find(fact=>fact.id==='q2.c1.scope').expected='평가 명제는 최초 일자의 보존이다. '+interpretation;
const file=path.join(base,'draft-12-560-freq01.json');
fs.writeFileSync(file,JSON.stringify(followup,null,2)+'\n',{flag:'wx'});
const qaSource=read(entry.qa_file),ids=['q2/omit-1','q2/model','q2/opposite','q2/date-only','q2/dual-date-one-sentence'];
const cases=ids.map(id=>qaSource.cases.find(sample=>sample.id===id));
if(cases.some(sample=>!sample))throw Error('Missing original QA case');
const qaFile=path.join(base,'qa-date-comparison.json');
fs.writeFileSync(qaFile,JSON.stringify({version:1,artifact_type:'author_expected_judgments',set_id:entry.set_id,draft_sha256:sha(file),live_model_grading:'not_run',human_approval:false,scope:'총괄 승인 c1 계약 표현 후속본의 동일 원 QA 5사례. 학생답안·기대값은 변경하지 않음.',cases},null,2)+'\n',{flag:'wx'});
const onlyChanged=structuredClone(followup),reset=Array.isArray(onlyChanged)?onlyChanged[0]:onlyChanged;
Object.assign(reset.subquestions.find(sub=>sub.id==='q2').criteria.find(criterion=>criterion.id==='q2.c1'),previousCriterion);
if(JSON.stringify(onlyChanged)!==JSON.stringify(original))throw Error('Unapproved changes beyond c1');
const lockFile=control+'/runtime-v4-stable/runtime-lock.json';
const prep={prepared_at:new Date().toISOString(),plan_id:entry.plan_id,authorization:'총괄의 T12-A 후속 criterion 명료화 및 v4 동일5사례×3 실제 재채점 지시',manifest:{file:manifestFile,sha256:sha(manifestFile)},predecessor:{file:entry.file,sha256:entry.sha256},candidate:{file,sha256:sha(file)},original_qa:{file:entry.qa_file,sha256:entry.qa_sha256,case_ids:ids},plan_files:entry.plan_files,source_files:entry.source_files,regression_qa:{file:qaFile,sha256:sha(qaFile)},required_runtime_lock:{file:lockFile,sha256:sha(lockFile)},disallowed_prior_runtime_lock_hashes:[],planned_cases:5,repetitions_each:3,planned_executions:15,api_calls_at_preparation:0,original_cases_identical:cases.every(sample=>JSON.stringify(sample)===JSON.stringify(qaSource.cases.find(item=>item.id===sample.id)))};
fs.writeFileSync(path.join(base,'preparation.json'),JSON.stringify(prep,null,2)+'\n',{flag:'wx'});
fs.writeFileSync(path.join(base,'lineage-and-diff.json'),JSON.stringify({recorded_at:new Date().toISOString(),predecessor:prep.predecessor,followup:prep.candidate,changes:[{path:'subquestions[q2].criteria[q2.c1].claim',before:previousCriterion.claim,after:criterion.claim},{path:'subquestions[q2].criteria[q2.c1].critical_facts[q2.c1.scope].expected',before:previousCriterion.critical_facts.find(fact=>fact.id==='q2.c1.scope').expected,after:criterion.critical_facts.find(fact=>fact.id==='q2.c1.scope').expected}],scope:'560.A13와 이전 c1.scope의 허용 함축을 주 claim에도 직접 명시. 평가명제·점수·발문·모범답안·원 QA 답안/기대값 변경 없음.',plan_reuse:{files:entry.plan_files,decision:'기존 계획 재사용 가능',reason:'판본·사례조건·물음요구·출처·독립명제·총점이 같고 c1의 기존 허용 범위를 주 claim과 동기화한 표현 보완이다. 새 문항 SHA로 의미검수 receipt는 별도 필요하다.'},only_c1_changed:true,points:7,subquestions:2,source_refs_unchanged:true,original_files_preserved:true},null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({candidate:file,sha256:sha(file),cases:cases.length,points:7,original_cases_identical:prep.original_cases_identical,api_calls:0}));
