import fs from 'node:fs';
import {createHash} from 'node:crypto';
import specs from './spec.mjs';
import {reviewedContentHash} from '../../../questionReviewIdentity.ts';
const dir='cpa_uploader/drafts/case-deepening-2026-09-14/b';
const batch='cpa_uploader/drafts/case-deepening-2026-09-14';
const catalogFile=`${batch}/source-catalog-final.json`, bankFile=`${batch}/bank-before.json`;
const catalog=JSON.parse(fs.readFileSync(catalogFile,'utf8')),bank=JSON.parse(fs.readFileSync(bankFile,'utf8'));
const hash=x=>createHash('sha256').update(x).digest('hex');
const unit=id=>{const u=catalog.units.find(u=>u.id===id);if(!u)throw Error(id);return u;};
const quote=id=>{const u=unit(id);let q=u.quote;
 // Preserve source files; trim only unrelated page markers, headers, and following section titles.
 if(['src-78146d7821a5d4d62f','src-b5fa93eb3674c68f23','src-e6693f2455af4ffdb3'].includes(id))q=q.split('\n=== PDF page')[0].trimEnd();
 if(id==='src-7fc068e3ee5ecaa39d')q=q.slice(0,q.lastIndexOf('가져야 한다.')+'가져야 한다.'.length);
 if(id==='src-a16ca292e24fc41f02')q=q.slice(0,q.indexOf('단 A18-A20 참조)')+'단 A18-A20 참조)'.length);
 if(id==='src-b0f4f9ece4907e4e7f')q=q.split('\n\n## PDF PAGE')[0].trimEnd();
 if(!fs.readFileSync(u.file,'utf8').includes(q))throw Error('nonexact '+id);return q;};
const lines=(f,a,b)=>fs.readFileSync(f,'utf8').split(/\r?\n/).slice(a-1,b).join('\n');
const latest='cpa_uploader/drafts/frequency-gap-2026-09-10/sources/kga-2026-pymupdf-pages.txt';
const pdf='cpa_uploader/drafts/frequency-gap-2026-09-10/sources/kga-2026-full.pdf';
const edition='2026년 1월 1일 개시 재무제표감사를 가정하고 공식 2026 전문의 501·530·560 본문·조건·예외를 직접 대조하였다. 2027년 날짜는 2026 재무제표의 후속 감사일자이다. 공식 2026 자료의 게시·시행 확인은 배치 raw 출처 계보를 함께 따른다. 501 A3/A7은 새로 등록한 2026 공식 발췌, 530·560은 동일한 2026 본문을 확인한 기존 공식 등록 전사에서 정확히 인용했다. 특정 미래 시험판본의 확정을 뜻하지 않는다.';

const sets=[],design=[],review=[],qa=[],usedFiles=new Set([latest,pdf,'cpa_uploader/raw/originals/case-deepening-2026-09-14/kga501-excerpts.md','cpa_uploader/raw/originals/case-deepening-2026-09-14/kga501-excerpts.provenance.json','cpa_uploader/raw/originals/case-deepening-2026-09-14/kga560-page-564.png']);

const addReading=(index,suffix,a,b,description)=>{const u=catalog.units.find(u=>u.file.endsWith(suffix)&&u.startLine<=a&&u.endLine>=b);if(!u)throw Error('reading range '+a+'-'+b);specs[index].learning.push([u.id,a,b,description]);};
addReading(0,'기출문제_연도별_해설_A.md',1789,1806,'2025 기출 문제7 물음2; p52 해설');
addReading(0,'고급_회계감사_연습.md',3932,3950,'2023 GS3 문제4 물음5·6; 고급연습p121 해설; 직접빈도에 합산하지 않는인접대조');
addReading(1,'기출문제_연도별_해설_A.md',17286,17305,'2017 기출 문제4 물음4; p437 해설');
addReading(1,'기출문제_연도별_해설_A.md',7728,7738,'2022 기출 문제4 물음4; p200 해설');
addReading(1,'고급_회계감사_연습.md',8723,8742,'2023 GS1 문제8; 고급연습p267 해설; 통제표본 인접대조');
addReading(2,'기출문제_연도별_해설_A.md',1254,1294,'2025 기출 문제4 물음3; p38 해설');
addReading(2,'고급_회계감사_연습.md',6749,6774,'2023 GS1 문제4 물음2·3; 고급연습p206 해설; 수정거부는이번직접요구가아님');
specs[2].latest.push([23888,23890,'KGA560.12의 각주6=KGA706, 문단13의 각주7=KGA705; PDF564']);

for(const spec of specs){
 const source_refs=spec.official.map(id=>{const u=unit(id);usedFiles.add(u.file);return{id,file:u.file,title:`${u.standard}.${u.paragraph}; ${u.locator}; 등록 판본 ${u.edition}; 2026 전문 대조는 design.json`,page:u.standard,source_quote:quote(id),role:'standard',content_hash:hash(quote(id))};});
 const set={schema_version:'3.0',id:spec.id,type:'linked_question_set',status:'needs_review',title:spec.title,classification:{topic_id:spec.topic,part:spec.part,chapter:spec.chapter,domain:'audit',standards:[...new Set(spec.official.map(id=>unit(id).standard))],tags:['사례형',spec.title]},source_refs,shared_context:{facts:spec.facts.map((text,i)=>({id:`fact${i+1}`,text,scoreable:false}))},learning_order:['sub1','sub2','sub3'],subquestions:[],verification:{source_fidelity:'reconstructed',review_status:'needs_human_review',calculation_required:false,notes:[edition,'작성자 agent가 원문·발문·답안·배점의 내용을 대조했다. 실제 모델 채점·사람 확인·게시·운영 반영은 아직 수행하지 않았으며 상위 배치에서 별도 확인한다.','모든 물음은 부모 사실의 적용을 요구하고 각 독립 의미 단위에 1점을 배정한다. 함축 판단을 인정하고 명시적 반대 판단과 독립적으로 맞는 근거를 구별한다.']}};
 for(const q of spec.questions){
  const sub={id:q.id,type:q.type,question_style:'case',topic_ids:q.topics,prompt:q.prompt,constraints:{ordered:false,max_entries:null,overflow_policy:'none'},selection:{type:'all',n:null},decision:null,answer_slots:[{id:`${q.id}.answer`,label:'답안',input:'textarea'}],model_answer:q.criteria.map(c=>c[0]),requirements:[],criteria:[]};
  q.criteria.forEach(([claim,sourceId,condition,extra=[]],i)=>{const id=`${q.id}.c${i+1}`,rid=`${q.id}.r${i+1}`;sub.requirements.push({id:rid,source_ref_id:sourceId,source_quote:quote(sourceId),source_span:`${unit(sourceId).locator}; 적용범위: ${condition}`});sub.criteria.push({id,requirement_id:rid,claim,critical_facts:[{id:`${id}.claim`,type:'action',expected:claim},{id:`${id}.scope`,type:'condition',expected:condition}],max_points:1,scores:{met:1,not_met:0,contradicted:0},source_ref_ids:[sourceId,...extra]});});
  set.subquestions.push(sub);
  const examples=['partial','wrong'].map(kind=>{const [answer,indices,reason]=q[kind];const row={set_id:set.id,subquestion_id:q.id,kind,answer,expected_points:indices.length,met_criterion_ids:indices.map(i=>`${q.id}.c${i}`),reason};qa.push(row);return row;});
  review.push({set_id:set.id,subquestion_id:q.id,reviewer_id:'agent:/root/next_cases_late',reviewed_at:new Date().toISOString(),method:'agent_content_review',human_review_performed:false,actual_model_grading:'not_run',criterion_ids:sub.criteria.map(c=>c.id),source_ref_ids:[...new Set(sub.criteria.flatMap(c=>c.source_ref_ids))],checks:{source:'pass',answer:'pass',prompt:'pass',points:'pass',style:'pass',topics:'pass',edition:'pass',nonduplication:'pass'},check_rationales:{source:`공식 본문과 criterion 보충 근거 ${[...new Set(sub.criteria.flatMap(c=>c.source_ref_ids))].join(', ')}를 직접 대조하였다. source_checks와 design의 2026 원문 범위를 함께 확인한다.`,answer:q.rationale,prompt:`요구 범위는 ${q.prompt} 이며 제외 범위를 모범답안에 숨겨 추가하지 않았다.`,points:q.point,style:`${q.facts.join(', ')}의 구체적 조건과 자료를 삭제하면 사례별 판단·방법을 결정할 수 없다. 일반 기준서 목록만으로 같은 만점 답안은 성립하지 않는다.`,topics:`실제 요구에 따라 ${q.topics.join(', ')}를 연결하였다. 부모 대표 주제만 복제하거나 사실에 잠깐 나타난 인접 주제를 추가하지 않았다.`,edition,nonduplication:spec.comparison.map(([id,d])=>`${id}: ${d}`).join(' ')},rationale:q.rationale,point_decision:q.point,max_points:sub.criteria.length,fact_ids:q.facts,question_style:'case',topic_ids:q.topics,minimal_sufficient_answer:sub.model_answer,source_checks:sub.requirements.map(r=>({requirement_id:r.id,source_ref_id:r.source_ref_id,source_span:r.source_span,exact_quote_checked:true,source_quote_sha256:hash(r.source_quote),verdict:'pass'})),criterion_checks:sub.criteria.map((c,i)=>({criterion_id:c.id,claim:c.claim,source_ref_ids:c.source_ref_ids,source_checks:c.source_ref_ids.map(id=>({source_ref_id:id,exact_quote_checked:true,quote_sha256:hash(quote(id)),locator:unit(id).locator})),independent_points:1,verdict:'pass',rationale:q.criteria[i][2]})),representative_qa_checks:examples,empty_answer:{expected_points:0,reason:'답안이 비어 있어 어떠한 정답 명제도 충족하지 않는다.'},unresolved_content_findings:[]});
 }
 const comparisons=spec.comparison.map(([id,difference])=>{const s=bank.find(s=>s.id===id);if(!s)throw Error(`comparison ${id}`);return{set_id:id,title:s.title,reviewed_content_hash:hash(JSON.stringify(s)),difference,questions:s.subquestions.map(q=>({id:q.id,prompt:q.prompt,model_answer:q.model_answer,criterion_ids:q.criteria.map(c=>c.id),points:q.criteria.reduce((a,c)=>a+c.max_points,0)}))};});
 const learning=spec.learning.map(([id,a,b,description])=>{const u=unit(id);usedFiles.add(u.file);const q=lines(u.file,a,b);return{source_unit_id:id,file:u.file,page:u.page,start_line:a,end_line:b,description,quote:q,quote_sha256:hash(q),file_sha256:hash(fs.readFileSync(u.file)),authority:u.authority,original_exam_pdf:'별도 공식 시험 PDF 원본을 새로 확보하지 않았으며 교재 수록 원발문·해설을 대조함',frequency_treatment:'기출과 모의를 구별하고 같은 원물음의 교재 재수록은 별도 출제로 더하지 않는다. 인접 요구의 빈도를 새 세부 요구에 전용하지 않는다.'};});
 const plan={version:1,topic_id:spec.topic,mode:spec.mode,objective:spec.objective,scope:{actors:['재무제표 감사인','경영진','재무제표 승인권자'],timing:['2026년 1월 1일 개시 재무제표감사; 부모 사실에 명시한 기간과 시점'],conditions:spec.facts,exceptions:[spec.exceptions],required_answers:spec.questions.map(q=>q.prompt),exclusions:[spec.exclusions]},question_types:[...new Set(spec.questions.map(q=>q.type))],source_unit_ids:[...new Set([...spec.official,...spec.learning.map(x=>x[0])])],existing_question_difference:comparisons.map(c=>`${c.set_id}: ${c.difference}`).join(' '),edition_assumption:edition,unresolved_items:[],status:'ready'};
 design.push({set_id:set.id,version:1,reviewer_id:'agent:/root/next_cases_late',reviewed_content_hash:hash(JSON.stringify(set)),content_hash:reviewedContentHash(set),plan,basis:{bank_file:bankFile,bank_sha256:hash(fs.readFileSync(bankFile)),source_catalog_file:catalogFile,source_catalog_sha256:hash(fs.readFileSync(catalogFile)),source_catalog_fingerprint:catalog.fingerprint,draft_inventory_file:`${batch}/draft-inventory.json`,draft_inventory_sha256:hash(fs.readFileSync(`${batch}/draft-inventory.json`)),comparison_inventory_file:`${dir}/comparison-inventory.json`},lineage:{kind:'new_case_adaptation',previous_set_id:null,previous_question_ids:[],new_subquestion_ids:['sub1','sub2','sub3'],preserves_existing_bank:true},compared_existing_sets:comparisons,learning_source_reading:learning,official_current_edition_comparison:spec.latest.map(([a,b,paragraphs])=>({file:latest,file_sha256:hash(fs.readFileSync(latest)),pdf_file:pdf,pdf_sha256:hash(fs.readFileSync(pdf)),start_line:a,end_line:b,paragraphs,quote:lines(latest,a,b),comparison_result:'2026 공식 전문에서 본문·조건·예외를 직접 읽고 기존 등록 전사의 채점 명제와 의미상 일치함을 확인했다.'})),source_evidence:source_refs.map(r=>({source_unit_id:r.id,file:r.file,file_sha256:hash(fs.readFileSync(r.file)),quote_sha256:hash(r.source_quote),locator:unit(r.id).locator,authority:unit(r.id).authority,quote_boundary:r.source_quote===unit(r.id).quote?'등록 단위의 정확한 인용':'등록 단위 내 완결된 해당 문단만 정확히 발췌; 무관한 추출 꼬리·쪽말 각주는 출처 파일을 수정하지 않고 인용범위에서 제외'})),mapping:spec.questions.map(q=>({subquestion_id:q.id,fact_ids:q.facts,objective:q.rationale,prompt:q.prompt,minimal_sufficient_answer:q.criteria.map(c=>c[0]),independent_requirements:q.criteria.map((c,i)=>({criterion_id:`${q.id}.c${i+1}`,claim:c[0],points:1,source_ref_ids:[c[1],...(c[3]??[])]})),necessary_description:'각 독립 명제에 필요한 설명만 요구한다. 문장 수나 답안 길이로 점수를 부여하지 않는다.',inference_burden:q.rationale,point_decision:q.point,decision:'유지',question_style:'case',topic_ids:q.topics})),facts_chars:[...set.shared_context.facts.map(f=>f.text).join('\n')].length,facts_measure:'facts text LF join, Unicode codepoints, spaces included',source_boundaries:{manual_scope:'530.6/.15/A23의 다음쪽 머리말,530.13/.14의 다음 소제목,560.12의 다음쪽 표시는 등록 파일을 수정하지 않고 완결 본문 인용에서만 제외했다. 501 A3의 각주4·5는 해당 문단이 인용하는 KGA600·620에 속하며, 각주를 A7의 요구로 옮기지 않았다. 기존 파일·카탈로그 원문은 바꾸지 않았다.',dependency_context:'501.4/A8,530.12/A17/A22,560.11 및12의관련범위를 공식2026전문에서 확인했다. 560.12의 강조사항문단6은 본문560.6이 아니라 PDF564의 각주6(KGA706)이며 원PDF화면과L23889에서 소유관계를 확인했다. 요구하지 않은700/706일반목록을 추가득점요건으로 넣지 않는다.'},unresolved_content_findings:[]});
 sets.push(set);
}
const draftInventoryFile=`${batch}/draft-inventory.json`;
const inv={method:'current_bank_and_preserved_drafts_semantic_comparison',bank_file:bankFile,bank_sha256:hash(fs.readFileSync(bankFile)),bank_set_count:bank.length,source_catalog_file:catalogFile,draft_inventory_file:draftInventoryFile,draft_inventory_sha256:hash(fs.readFileSync(draftInventoryFile)),machine_inventory_interpretation:'기계목록의 정본 미편입9개ID는 과거frequency-gap 초안이며 단순ID부재를 진행중신규로세지 않는다. 목록생성과 본문직접대조는 구별한다.',current_comparisons:design.flatMap(d=>d.compared_existing_sets.map(s=>({new_set_id:d.set_id,compared_set_id:s.set_id,difference:s.difference}))),notes:['구체 근접문항의 발문·답안·criterion을 직접 읽고 차이를 각set계획에기록했다.','미편입소극조회·서비스조직·기타정보·비교정보·의견·부정/커뮤니케이션 과거초안은 신규3개의직접요구와다르다.','후속사건기존일반형draft-12-560-freq01과기중실사draft-09-501-freq01은현행정본문항이다.']};
fs.writeFileSync(`${dir}/comparison-inventory.json`,JSON.stringify(inv,null,2)+'\n');
for(const d of design)d.basis.comparison_inventory_sha256=hash(fs.readFileSync(`${dir}/comparison-inventory.json`));
const boundaryFile=`${dir}/qa-boundaries.json`;
const boundaryChecks=JSON.parse(fs.readFileSync(boundaryFile,'utf8'));
for(const row of review)row.boundary_qa_checks=boundaryChecks.filter(x=>x.set_id===row.set_id&&x.subquestion_id===row.subquestion_id);
const fileRows=[...usedFiles].map(file=>({file,sha256:hash(fs.readFileSync(file))}));
for(const name of fs.readdirSync(`${dir}/sources`).filter(x=>x.endsWith('.png'))){const file=`${dir}/sources/${name}`;fileRows.push({file,sha256:hash(fs.readFileSync(file)),role:'rendered_visual_verification',source_file:pdf});}
for(const [f,d] of [['sets.json',sets],['design.json',design],['review.json',review],['qa.json',qa],['source-files.json',fileRows]])fs.writeFileSync(`${dir}/${f}`,JSON.stringify(d,null,2)+'\n');
console.log(JSON.stringify({sets:sets.map(s=>({id:s.id,fact_characters:[...s.shared_context.facts.map(f=>f.text).join('\n')].length,points:s.subquestions.reduce((a,q)=>a+q.criteria.length,0)})),review_rows:review.length,qa_rows:qa.length}));

const dataset=JSON.parse(fs.readFileSync('cpa_uploader/analysis/question-elements/question-elements.json','utf8'));
const coverage=specs.map(spec=>{const e=dataset.elements.find(e=>e.id===spec.coverage.element_id),set=sets.find(s=>s.id===spec.id),q=set.subquestions.find(q=>q.id===spec.coverage.question);if(!e)throw Error(spec.coverage.element_id);const os=dataset.occurrences.filter(o=>e.occurrence_ids.includes(o.id));return {element_id:e.id,set_id:set.id,subquestion_id:q.id,criterion_ids:q.criteria.map(c=>c.id),relation:spec.coverage.relationship,reason:spec.coverage.reason,source_unit_ids:[...new Set(q.criteria.flatMap(c=>c.source_ref_ids))],original_question_ids:e.exam_questions??[],source_record_ids:[...new Set(os.map(o=>o.record_id))],frequency_kind:'exam',reprint_treatment:'같은 원물음의 교재 재수록을 제외하고 실제 서로 다른 출제를 유지한다. ADV 인접요구는 직접기출빈도에 합산하지 않는다.',source_locations:spec.learning.filter(x=>!unit(x[0]).file.includes('03_문제연습')).map(([id,a,b])=>({file:unit(id).file,start_line:a,end_line:b,page:unit(id).page}))};});
fs.writeFileSync(`${dir}/coverage-proposals.json`,JSON.stringify(coverage,null,2)+'\n');
