import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {reviewedContentHash} from '../../../questionReviewIdentity.ts';
import spec from './spec.mjs';
const batch='cpa_uploader/drafts/case-trio-next-2026-09-14',dir=`${batch}/b`;
const read=f=>JSON.parse(fs.readFileSync(f,'utf8')),hash=v=>createHash('sha256').update(v).digest('hex'),fileHash=f=>hash(fs.readFileSync(f));
const catalogFile=`${batch}/source-catalog.json`,bankFile=`${batch}/bank-before.json`,inventoryFile=`${batch}/draft-inventory.json`,elementFile='cpa_uploader/analysis/question-elements/question-elements.json';
const cat=read(catalogFile),bank=read(bankFile),inventory=read(inventoryFile),dataset=read(elementFile);
const latest='cpa_uploader/drafts/frequency-gap-2026-09-10/sources/kga-2026-pymupdf-pages.txt',pdf='cpa_uploader/drafts/frequency-gap-2026-09-10/sources/kga-2026-full.pdf';
const learningA='cpa_uploader/data/회계감사_통합학습자료/04_기출문제/기출문제_연도별_해설_A.md',advanced='cpa_uploader/data/회계감사_통합학습자료/03_문제연습/고급_회계감사_연습.md';
const unit=id=>{const u=cat.units.find(u=>u.id===id);if(!u)throw Error(id);return u;};
const lines=(f,a,b)=>fs.readFileSync(f,'utf8').split(/\r?\n/).slice(a-1,b).join('\n');
const quote=id=>{const u=unit(id);let q=u.quote;if(u.paragraph==='5')q=q.split('\n감사 진행 중')[0];if(u.paragraph==='A2')q=q.split('\n개별재무제표')[0];q=q.split(/\r?\n\r?\n## PDF PAGE/)[0].trimEnd();if(!fs.readFileSync(u.file,'utf8').includes(q))throw Error(`source quote mismatch ${id}`);return q;};
const edition='2026년 1월 1일 개시 보고기간의 재무제표감사이다. 기존 2025 등록 전사의450.5/A2/A19/A20을 재사용하고, 2026 공식 전문 PDF383·384·386·387·390에서 시행일·본문·조건·각주 위치를 직접 대조했다. 사용하는 채점 명제에 판본 차이가 없으며 미래 시험의 적용 판본 확정을 뜻하지 않는다.';
const sourceBoundary={manual_scope:'2026 전문에서450.2/5/11, A2~A6, A19~A20 및 A19 각주13을 직접 읽었다. 직접 득점 근거는 등록450.5/A2/A19/A20이다. 새 공식 전사를 만들거나 기존 등록 바이트를 수정하지 않았다.',dependency_context:'A19의 동일 계정잔액·거래유형 내 중요하지 않은 오류 상계 가능성과 추가 미발견위험 고려를 읽었다. 각주13(L16719~16720, PDF390)은 등록 A19의 끝에 번호만 있고 본문이 없어 수동 근거 장부에 보존한다. 각주13은 A21 소유가 아니며 이번 서로 다른 중요 오류의 상계 판단에 추가 독립 점수로 요구하지 않는다. 450.5의 A3~A6 연결은 PDF386~387의 문맥을 직접 대조했다. A3 중간의 각주6~8은 A1의 공시·부정 문맥이므로 A3의 실제 득점 의존으로 오인하지 않는다.',unresolved_marker:'A2 본문의 (*1)은 원PDF386에도 인쇄되어 있고 별도 설명은 확보된 전체 전문의 검색에서 찾지 못했다. 그 표시의 내용을 추정하지 않는다. 새 sub1의 직접 논거는 A2 마지막의 불확실성에 관한 완결 문장과450.5의 집계 요구이다. 이 표시를 누락한 수정 전사를 만들지 않았으며 해당 표시의 해명까지 완료했다고 주장하지 않는다.',scope_resolved:true};
const source_refs=spec.official.map(id=>{const u=unit(id);return{id,file:u.file,title:`${u.standard} ${u.paragraph}; 등록 전사 문단. 2026 대조 페이지·행은 design.json`,page:u.standard,source_quote:quote(id),role:'standard',content_hash:hash(quote(id))};});
const set={schema_version:'3.0',id:spec.id,type:'linked_question_set',status:'needs_review',title:spec.title,classification:{topic_id:spec.topic,part:spec.part,chapter:spec.chapter,domain:'audit',standards:['KGA 450'],tags:['사례형','명백하게 사소','분류왜곡표시','질적 중요성','상계']},source_refs,shared_context:{facts:spec.facts.map((text,i)=>({id:`fact${i+1}`,text,scoreable:false}))},learning_order:['sub1','sub2','sub3'],subquestions:[],verification:{source_fidelity:'reconstructed',review_status:'needs_human_review',calculation_required:false,notes:[edition,'기출·고급연습의 평가 관점을 바탕으로 새 사실을 재구성했다. 원 시험의 동일 문제라고 주장하지 않는다.','작성자 agent 의미검수·부분점수 검토를 기록하며 실제 모델 채점·사람 확인·정본·공개본·운영 DB는 상위 배치의 별도 증거로 확인한다.']}};
const qa=[],review=[],boundary=[];
const addBoundary=(q,kind,answer,indices,reason)=>boundary.push({set_id:set.id,subquestion_id:q,kind,answer,expected_points:indices.length,met_criterion_ids:indices.map(i=>`${q}.c${i}`),reason,actual_model_grading:'not_run',method:'agent_expected_score_review'});
for(const q of spec.questions){
 const sub={id:q.id,type:q.type,question_style:'case',topic_ids:q.topics,prompt:q.prompt,constraints:{ordered:false,max_entries:null,overflow_policy:'none'},selection:{type:'all',n:null},decision:null,answer_slots:[{id:`${q.id}.answer`,label:'답안',input:'textarea'}],model_answer:q.criteria.map(c=>c[0]),requirements:[],criteria:[]};
 q.criteria.forEach(([claim,sid,condition,extra=[]],i)=>{const id=`${q.id}.c${i+1}`,rid=`${q.id}.r${i+1}`;sub.requirements.push({id:rid,source_ref_id:sid,source_quote:quote(sid),source_span:`${unit(sid).locator}; ${condition}`});sub.criteria.push({id,requirement_id:rid,claim,critical_facts:[{id:`${id}.claim`,type:'action',expected:claim},{id:`${id}.scope`,type:'condition',expected:condition}],max_points:1,scores:{met:1,not_met:0,contradicted:0},source_ref_ids:[sid,...extra]});});
 set.subquestions.push(sub);
 const examples=['partial','wrong'].map(kind=>{const[answer,ids,reason]=q[kind];const x={set_id:set.id,subquestion_id:q.id,kind,answer,expected_points:ids.length,met_criterion_ids:ids.map(i=>`${q.id}.c${i}`),reason};qa.push(x);return x;});
 addBoundary(q.id,'conclusion_only',q.criteria[0][0],[1],'판단만 남기고 독립 근거를 삭제하였으므로 1점이다.');
 addBoundary(q.id,'implied_judgment',q.criteria[1][0],[1,2],'올바른 구체적 근거가 담당자의 처리와 반대되는 판단을 분명히 함축하므로 판단 문구를 생략해도 2점이다. 명시적 반대 판단이 없는 경우이다.');
 addBoundary(q.id,'explicit_opposite_with_correct_reason',q.wrong[0]+' 다만 '+q.criteria[1][0],[2],'명시적인 반대 결론 때문에 c1은 0점이나 독립적으로 맞는 구체적 이유 c2는 1점이다.');
 addBoundary(q.id,'generic_only',q.id==='sub1'?'명백하게 사소한 것을 제외하고 왜곡표시를 집계한다.':q.id==='sub2'?'분류왜곡표시에는 질적인 평가도 필요하다.':'개별적 또는 집합적으로 중요한지 평가한다.',[],'추상적 규칙만 제시하고 어느 사례 사실에 어떻게 적용할지를 말하지 않아 사례의 판단·근거가 충족되지 않는다.');
 review.push({set_id:set.id,subquestion_id:q.id,reviewer_id:'agent:/root/followup_sources_b',reviewed_at:new Date().toISOString(),method:'agent_content_review',human_review_performed:false,actual_model_grading:'not_run',criterion_ids:sub.criteria.map(c=>c.id),source_ref_ids:[...new Set(sub.criteria.flatMap(c=>c.source_ref_ids))],checks:{source:'pass',answer:'pass',prompt:'pass',points:'pass',style:'pass',topics:'pass',edition:'pass',nonduplication:'pass'},check_rationales:{source:sourceBoundary.manual_scope+' '+sourceBoundary.dependency_context,answer:q.rationale,prompt:'각 물음은 해당 사례의 판단과 그 이유에 한정하고 금액 계산·후속절차·보고의견 등 다른 요구를 묶지 않았다.',points:q.point,style:`${q.facts.join(', ')}의 반복 범위·분류 영향 또는 서로 다른 오류에 관한 사실을 지우면 동일한 만점 답안이 성립하지 않는다.`,topics:'12 감사의 마무리의450 왜곡표시 집계·평가. 기초 사실에 매출·자산이 있다는 이유만으로 관련 계정 감사절차 주제를 추가하지 않는다.',edition,nonduplication:spec.comparison.map(x=>x.join(': ')).join(' ')},rationale:q.rationale,point_decision:q.point,max_points:2,fact_ids:q.facts,question_style:'case',topic_ids:q.topics,minimal_sufficient_answer:sub.model_answer,source_checks:sub.requirements.map(r=>({requirement_id:r.id,source_ref_id:r.source_ref_id,source_span:r.source_span,exact_quote_checked:true,source_quote_sha256:hash(r.source_quote),verdict:'pass'})),criterion_checks:sub.criteria.map((c,i)=>({criterion_id:c.id,claim:c.claim,source_ref_ids:c.source_ref_ids,independent_points:1,verdict:'pass',rationale:q.criteria[i][2]})),representative_qa_checks:examples,empty_answer:{expected_points:0,reason:'판단과 근거가 모두 없다.'},unresolved_content_findings:[]});
}
addBoundary('sub1','scope_uncertainty_reversal','같은 코드의 반복 사용 범위와 합계 영향이 모두 조사되어 어느 기준으로 보아도 명백하게 미미하다는 증거가 있다면 집계에서 제외할 수 있겠지만, 이 사례는 그 영향이 아직 미확인되어 세 건도 집계해야 한다.',[1,2],'현재 미확인 상태와 조건을 바꾼 가정을 구별했으므로 현재 사례의 판단과 근거 모두 충족한다.');
addBoundary('sub2','income_only_shortcut','손익이 바뀌지 않는 모든 분류오류는 언제나 중요하지 않으므로 이 건도 중요하지 않다.',[1],'현 사례의 결론 자체는 맞아 1점이나 모든 분류오류에 대한 일반화는 올바른 질적 근거가 아니다.');
addBoundary('sub3','offset_exception_distinction','각각 중요한 매출과 광고비가 다른 계정에 과대계상되어 남으므로 이익이 같더라도 재무제표는 중요하게 왜곡된다. 같은 계정 안의 작은 오류를 조건에 따라 상계할 수 있다는 예외를 여기에 적용할 수 없다.',[1,2],'전체 상계를 언제나 금지한다고 일반화하지 않고 현재 각기 중요한 다른 항목의 오류를 구별한다.');
for(const r of review)r.boundary_qa_checks=boundary.filter(x=>x.subquestion_id===r.subquestion_id);
const learningRanges=[
 [learningA,6361,6361,'2023 문제10 공통지문; p167'],[learningA,6403,6416,'2023 문제10 물음3 전체 요구·항목; p168. 직접 관련① 집계 예외'],[learningA,6566,6597,'2023 문제10 물음3 답안 및①의 근거; p171. 상계 설명은 해설의 보충 내용이며 원①의 별도 출제 요구로 세지 않는다.'],
 [learningA,7040,7042,'2022 문제2 공통지문; p182'],[learningA,7060,7096,'2022 문제2 물음3 전체 요구·항목·답안양식; p182~183. 직접 관련②이며 나머지 항목은 신규에 전용하지 않는다.'],[learningA,7190,7214,'2022 문제2 물음3 전체 정오답 및②의 완결 근거; p186. 다른 항목의 근거는 신규 채점에 사용하지 않는다.'],
 [advanced,4250,4280,'2024 GS1 문제4 공통사실·항목A~D·물음1~2; p130. 새 문항에 직접 사용하는 것은 B와 연결된 물음3이다.'],[advanced,4285,4294,'동일 문제 물음3 전체 대화·원발문; p131'],[advanced,4342,4356,'동일 문제 물음3 답안·A20 해설·채점 유의; p132'],[advanced,12123,12139,'동일 문제 물음3 재수록; p334. 새 출제로 합산하지 않는다.'],[advanced,17171,17185,'동일 해설 재수록. 원래 해설과 같은 범위이며 빈도로 더하지 않는다.']
];
const learning=learningRanges.map(([file,a,b,description])=>{const us=cat.units.filter(u=>u.file===file&&u.startLine<=b&&u.endLine>=a);if(!us.length)throw Error(`no source units ${a}`);return{source_unit_ids:us.map(u=>u.id),source_unit_id:us[0].id,file,start_line:a,end_line:b,page:us[0].page,description,quote:lines(file,a,b),quote_sha256:hash(lines(file,a,b)),file_sha256:fileHash(file),original_exam_pdf:'원 시험 PDF는 이 배치에서 별도로 대조하지 않았다. 출제 식별이 있는 학습자료 수록 발문·공통사실·해설을 직접 대조했다.',frequency_treatment:'실제 기출, GS 모의 및 동일 원물음의 재수록을 구별한다. 해설에만 있는 설명을 추가 원발문 요구로 세지 않는다.'};});
const comparisons=spec.comparison.map(([id,difference])=>{const s=bank.find(s=>s.id===id);if(!s)throw Error(id);return{set_id:id,title:s.title,reviewed_content_hash:hash(JSON.stringify(s)),difference,questions:s.subquestions.map(q=>({id:q.id,prompt:q.prompt,model_answer:q.model_answer,criteria:q.criteria,points:q.criteria.reduce((a,c)=>a+c.max_points,0)}))};});
const relatedBank=bank.filter(s=>s.classification.standards.includes('KGA 450'));
const comparedDrafts=inventory.rows.filter(r=>r.questions.some(q=>q.topics?.includes('12'))).map(r=>({...r,difference:r.id==='pilot-12-009'?spec.comparison.find(x=>x[0]===r.id)[1]:'580 서면진술·560 후속사건·570 계속기업에 관한 물음으로450 집계/분류/상계와 요구가 다르다.'}));
const comparisonInventory={method:'inventory_filter_then_agent_read_of_nearby_questions_answers_and_criteria',bank_file:bankFile,bank_sha256:fileHash(bankFile),bank_sets:bank.length,draft_inventory_file:inventoryFile,draft_inventory_sha256:fileHash(inventoryFile),current_450_sets:relatedBank.map(s=>({id:s.id,title:s.title,content_hash:hash(JSON.stringify(s)),questions:s.subquestions.map(q=>({id:q.id,prompt:q.prompt,model_answer:q.model_answer,criteria:q.criteria})),difference:spec.comparison.find(x=>x[0]===s.id)?.[1]??'경영진·지배기구 커뮤니케이션, 경영진 수정요청 또는 서면진술의 일반 요구로 신규의 구체적 집계·평가 판단과 구별된다.'})),related_draft_records:comparedDrafts,limits:'정본 관련450 전 물음의 발문·모범·criteria와 가까운 pilot-12-009 과거 초안,표본변이 사례를 직접 대조했다. 기타 주제12 초안은 요구 종류를 확인했으며 모든 역사적 파일의 독립 재검수를 완료한 것으로 주장하지 않는다.'};
const latestRanges=[[16392,16394,'450.2; PDF383'],[16426,16428,'450.5; PDF384'],[16458,16474,'450.11; PDF384~385. 중간각주3은450.8 소유'],[16531,16540,'450.A2; PDF386'],[16542,16560,'450.A3; PDF386~387. 중간각주6~8은A1 소유'],[16562,16588,'450.A4~A6; PDF387'],[16691,16704,'450.A19~A20; PDF390'],[16719,16720,'450.A19 각주13; PDF390']];
const plan={version:1,topic_id:'12',mode:'adapt_existing_question',objective:'발견된 오류에 대한 명백하게 사소함의 집계 예외, 분류왜곡표시의 질적 평가 및 서로 다른 중요 오류의 상계 한계를 실제 증거상태에 적용한다.',scope:{actors:['세림유통의 감사인','담당 감사팀원'],timing:['2026년1월1일 개시 재무제표감사의 왜곡표시 집계·평가 시점'],conditions:spec.facts,exceptions:['금액만으로 집계 제외를 정하지 않는다. 분류왜곡표시가 전체 중요성을 넘더라도 질적 영향의 조건에 따라 중요하지 않을 수 있다. 같은 계정 내 작은 오류의 상계 예외를 서로 다른 중요한 오류에 적용하지 않는다.'],required_answers:spec.questions.map(q=>q.prompt),exclusions:['금액 계산, 표본 투영, 추가절차의 설계, 경영진 수정요청, 전기 오류와 중요성 재평가, 최종 감사의견은 요구하지 않는다.']},question_types:['descriptive'],source_unit_ids:[...new Set([...spec.official,...learning.flatMap(x=>x.source_unit_ids)])],existing_question_difference:spec.comparison.map(x=>x.join(': ')).join(' '),edition_assumption:edition,unresolved_items:[],status:'ready'};
const design=[{set_id:set.id,version:1,reviewer_id:'agent:/root/followup_sources_b',reviewed_content_hash:hash(JSON.stringify(set)),content_hash:reviewedContentHash(set),plan,basis:{bank_file:bankFile,bank_sha256:fileHash(bankFile),source_catalog_file:catalogFile,source_catalog_sha256:fileHash(catalogFile),source_catalog_fingerprint:cat.fingerprint,draft_inventory_file:inventoryFile,draft_inventory_sha256:fileHash(inventoryFile),comparison_inventory_file:`${dir}/comparison-inventory.json`},lineage:{kind:'new_case_adaptation',previous_set_id:null,previous_question_ids:[],new_subquestion_ids:['sub1','sub2','sub3'],preserves_existing_bank:true},compared_existing_sets:comparisons,learning_source_reading:learning,official_current_edition_comparison:latestRanges.map(([a,b,paragraphs])=>({file:latest,file_sha256:fileHash(latest),pdf_file:pdf,pdf_sha256:fileHash(pdf),start_line:a,end_line:b,paragraphs,quote:lines(latest,a,b),comparison_result:'본문·조건을 직접 대조했으며 원문 각주 소유 및 표시의 한계는 source_boundaries에 기록했다.'})),source_evidence:source_refs.map(r=>({source_unit_id:r.id,file:r.file,file_sha256:fileHash(r.file),quote_sha256:hash(r.source_quote),locator:unit(r.id).locator,authority:unit(r.id).authority,quote_boundary:'등록 문단 본문만 인용하고 뒤의 제목·다음쪽 색인은 잘라냈다. 원파일 바이트는 보존했다.'})),mapping:spec.questions.map(q=>({subquestion_id:q.id,fact_ids:q.facts,objective:q.rationale,prompt:q.prompt,minimal_sufficient_answer:q.criteria.map(c=>c[0]),independent_requirements:q.criteria.map((c,i)=>({criterion_id:`${q.id}.c${i+1}`,claim:c[0],points:1,source_ref_ids:[c[1],...(c[3]??[])]})),necessary_description:'짧은 판단 및 사례의 결정적인 근거를 연결한다. 같은 근거가 판단을 함축하면 별도 판단 표기 없이도 인정한다.',inference_burden:q.rationale,point_decision:q.point,decision:'유지',question_style:'case',topic_ids:q.topics})),facts_chars:[...spec.facts.join('\n')].length,facts_measure:'facts text LF join, Unicode codepoints, spaces included',source_boundaries:sourceBoundary,local_regression_expectations:boundary,unresolved_content_findings:[]}];
const provenance={method:'existing_registered_transcription_and_current_pdf_direct_comparison',agent:'agent:/root/followup_sources_b',human_review_performed:false,new_official_transcription_created:false,registered_files:[...new Set(source_refs.map(x=>x.file))].map(file=>({file,sha256:fileHash(file)})),current_pdf:{file:pdf,sha256:fileHash(pdf),extraction:latest,extraction_sha256:fileHash(latest)},visuals:[383,384,386,387,390].map(page=>{const file=`${dir}/sources/kga450-page-${page}.png`;return{file,sha256:fileHash(file),source:pdf,page,command:`pdftoppm -f ${page} -singlefile -scale-to 1500 -png`,inspection:'agent가 실제 화면의 문단·조건·각주·쪽 경계를 확인했다.'};}),source_boundaries:sourceBoundary,asterisk_marker_search:{file:latest,file_sha256:fileHash(latest),scope:'1001쪽 전체 공식 전문 추출 텍스트에서 문자 (*1) 검색. PDF386 시각 대조도 수행했다.',matches:fs.readFileSync(latest,'utf8').split(/\r?\n/).map((text,i)=>({line:i+1,text})).filter(x=>x.text.includes('(*1)')),interpretation:'450 범위에서는 L16537 본문의 표시 하나뿐이며, 다른 위치의 (*1) 표시는570·600·701의 각각 다른 문단·설명에 속한다. 450.A2에 대응하는 별도 설명을 확인하지 못했다. 그 내용을 다른 기준서에서 가져오거나 추정하지 않는다. 이번 답안은 표시 없는 마지막 불확실성 문장으로 완결되어 채점 범위에는 영향이 없다.'},notes:['새 이미지들은 기존 보존 원PDF에서 파생되었다. root의 raw 최종 수집 목록에 연결하도록 source-files에 기록한다. 원 시험 PDF를 확보하거나 확인한 것으로 표시하지 않는다.']};
const e=dataset.elements.find(e=>e.id===spec.coverage.element_id),oc=dataset.occurrences.filter(o=>e.occurrence_ids.includes(o.id)),records=dataset.records.filter(r=>oc.some(o=>o.record_id===r.id)),q=set.subquestions.find(q=>q.id===spec.coverage.question);
const coverage=[{element_id:e.id,set_id:set.id,subquestion_id:q.id,criterion_ids:spec.coverage.criteria,relationship:spec.coverage.relationship,reason:spec.coverage.reason,review_status:'needs_review',target:{file:`${dir}/sets.json`,scope:'draft'},source_unit_ids:['src-01687c0080d5ac194b'],original_question_ids:oc.map(o=>o.question_key),source_record_ids:records.map(r=>r.id),frequency_kind:'mock',reprint_treatment:'2024 GS1 문제4 물음3 원출제 한 번. 고급연습 p131과334 재수록 및 해설의 반복은 추가 출제로 세지 않는다. 기출2022/2023은 별개의 참고 관계이며 이 모의의 직접 요구에 합산하지 않는다.',source_locations:learning.filter(x=>x.file===advanced).map(x=>({file:x.file,start_line:x.start_line,end_line:x.end_line,page:x.page})),snapshot:{question_hash:hash(JSON.stringify(q)),question_source_hash:hash(JSON.stringify(source_refs)),question_metadata_hash:hash(JSON.stringify({question_style:q.question_style,topic_ids:q.topic_ids})),element_hash:hash(JSON.stringify(e)),source_record_hashes:Object.fromEntries(records.map(r=>[r.id,hash(JSON.stringify(r))])),target_file_sha256:null},provenance:{agent:'agent:/root/followup_sources_b',human_review_performed:false,element_file:elementFile,element_file_sha256:fileHash(elementFile),original_records:records,occurrences:oc,manual_reason:'원 대화 L4286~4294·답안 L4342~4356과 재수록 L12123~12139·L17171~17185를 직접 읽었다. 원 대화의 분류 조건은 재구성하지만 판단+질적 이유의 요구 범위를 모두 다루어 direct이다.'}}];
const write=(f,v)=>fs.writeFileSync(`${dir}/${f}`,JSON.stringify(v,null,2)+'\n');
write('comparison-inventory.json',comparisonInventory);design[0].basis.comparison_inventory_sha256=fileHash(`${dir}/comparison-inventory.json`);
write('sets.json',[set]);coverage[0].snapshot.target_file_sha256=fileHash(`${dir}/sets.json`);
write('design.json',design);write('review.json',review);write('qa.json',qa);write('qa-boundaries.json',boundary);write('coverage-proposals.json',coverage);write('sources/provenance.json',provenance);
const files=[...new Set([latest,pdf,learningA,advanced,...source_refs.map(x=>x.file),...provenance.visuals.map(x=>x.file),`${dir}/sources/provenance.json`])];
write('source-files.json',files.map(file=>({file,sha256:fileHash(file)})));
console.log(JSON.stringify({sets:1,questions:3,points:6,facts_chars:design[0].facts_chars,qa_rows:qa.length,boundary_rows:boundary.length}));
