import fs from 'node:fs';
import {createHash} from 'node:crypto';
import spec from './spec.mjs';
import {reviewedContentHash} from '../../../questionReviewIdentity.ts';
const batch='cpa_uploader/drafts/case-trio-2026-09-14',dir=`${batch}/b`;
const catalogFile=`${batch}/source-catalog.json`,bankFile=`${batch}/bank-before.json`,inventoryFile=`${batch}/draft-inventory.json`;
const read=f=>JSON.parse(fs.readFileSync(f,'utf8')),hash=v=>createHash('sha256').update(v).digest('hex');
const cat=read(catalogFile),bank=read(bankFile),inventory=read(inventoryFile),elementFile='cpa_uploader/analysis/question-elements/question-elements.json',dataset=read(elementFile);
const unit=id=>{const u=cat.units.find(u=>u.id===id);if(!u)throw Error(id);return u;};
const lines=(file,a,b)=>fs.readFileSync(file,'utf8').split(/\r?\n/).slice(a-1,b).join('\n');
const boundaryHeadings={9:'감사인측 전문가의 전문분야에 대한 이해',10:'감사인측 전문가와의 합의',11:'감사인측 전문가 업무의 적합성 평가',A20:'감사인측 전문가의 전문분야에 대한 이해',A22:'감사인측 전문가와의 합의'};
const quote=id=>{const u=unit(id);let q=u.quote.split('\n\n\n\n## PDF PAGE')[0];if(boundaryHeadings[u.paragraph])q=q.split('\n'+boundaryHeadings[u.paragraph])[0];q=q.trimEnd();if(!fs.readFileSync(u.file,'utf8').includes(q))throw Error(`not exact ${id}`);return q;};
const latest='cpa_uploader/drafts/frequency-gap-2026-09-10/sources/kga-2026-pymupdf-pages.txt',pdf='cpa_uploader/drafts/frequency-gap-2026-09-10/sources/kga-2026-full.pdf';
const learningA='cpa_uploader/data/회계감사_통합학습자료/04_기출문제/기출문제_연도별_해설_A.md',advanced='cpa_uploader/data/회계감사_통합학습자료/03_문제연습/고급_회계감사_연습.md';
const edition='2026년 1월 1일 개시 재무제표감사의 전문가 선정·착수 전 상황이다. 공식 2026 전문 PDF683 및689~693에서 620.9~11, A14~A31을 읽고, 직접 인용하는 2025 등록 전사 9~11/A14/A17~A22의 채점 명제가 현행 해당 문구와 동일함을 확인했다. A15 말미의 품질관리정책·절차→품질관리시스템 판본 차이를 인지하여 그 항목은 직접 인용·득점 요구에서 제외했다. 특정 미래 시험판본의 확정을 의미하지 않는다.';
const source_refs=spec.official.map(id=>{const u=unit(id);return{id,file:u.file,title:`${u.standard} ${u.paragraph}; 2025 등록 전사 PDF${u.page}; 2026 원문 대조는 design.json`,page:u.standard,source_quote:quote(id),role:'standard',content_hash:hash(quote(id))};});
const set={schema_version:'3.0',id:spec.id,type:'linked_question_set',status:'needs_review',title:spec.title,classification:{topic_id:spec.topic,part:spec.part,chapter:spec.chapter,domain:'audit',standards:['KGA 620'],tags:['사례형','감사인측 외부전문가','적격성','객관성','전문분야 이해','업무 합의']},source_refs,shared_context:{facts:spec.facts.map((text,i)=>({id:`fact${i+1}`,text,scoreable:false}))},learning_order:['sub1','sub2','sub3'],subquestions:[],verification:{source_fidelity:'reconstructed',review_status:'needs_human_review',calculation_required:false,notes:[edition,'신규 사례는 기출·고급연습의 평가 관점을 참고하여 재구성했다. 원 시험과 동일한 문제라는 뜻이 아니다.','작성자 agent의 직접 의미검수이며, 실제 모델 채점·사람 확인·게시·운영 반영은 상위 배치에서 별도로 수행한다.']}};
const qa=[],review=[];
for(const q of spec.questions){
 const sub={id:q.id,type:q.type,question_style:'case',topic_ids:q.topics,prompt:q.prompt,constraints:{ordered:false,max_entries:null,overflow_policy:'none'},selection:{type:'all',n:null},decision:null,answer_slots:[{id:`${q.id}.answer`,label:'답안',input:'textarea'}],model_answer:q.criteria.map(c=>c[0]),requirements:[],criteria:[]};
 q.criteria.forEach(([claim,sourceId,condition,extra=[]],i)=>{const id=`${q.id}.c${i+1}`,rid=`${q.id}.r${i+1}`;sub.requirements.push({id:rid,source_ref_id:sourceId,source_quote:quote(sourceId),source_span:`${unit(sourceId).locator}; 사용 범위: ${condition}`});sub.criteria.push({id,requirement_id:rid,claim,critical_facts:[{id:`${id}.claim`,type:'action',expected:claim},{id:`${id}.scope`,type:'condition',expected:condition}],max_points:1,scores:{met:1,not_met:0,contradicted:0},source_ref_ids:[sourceId,...extra]});});
 set.subquestions.push(sub);
 const examples=['partial','wrong'].map(kind=>{const [answer,indices,reason]=q[kind];const x={set_id:set.id,subquestion_id:q.id,kind,answer,expected_points:indices.length,met_criterion_ids:indices.map(i=>`${q.id}.c${i}`),reason};qa.push(x);return x;});
 review.push({set_id:set.id,subquestion_id:q.id,reviewer_id:'agent:/root/followup_sources_b',reviewed_at:new Date().toISOString(),method:'agent_content_review',human_review_performed:false,actual_model_grading:'not_run',criterion_ids:sub.criteria.map(c=>c.id),source_ref_ids:[...new Set(sub.criteria.flatMap(c=>c.source_ref_ids))],checks:{source:'pass',answer:'pass',prompt:'pass',points:'pass',style:'pass',topics:'pass',edition:'pass',nonduplication:'pass'},check_rationales:{source:'등록 620 원문과 2026 공식 전문을 본문·조건·예외까지 직접 대조했다. 11(c)(d)의 관련 적용자료 A30·A31은 공식 PDF693에서 확인했으며, 새 source unit으로 등록하지 않은 자료를 존재하는 ID로 꾸미지 않았다.',answer:q.rationale,prompt:'부모 사실에 있는 자료를 사용하고 발문이 지정한 평가·이해·합의 범위에 득점 요구를 한정했다.',points:q.point,style:`${q.facts.join(', ')}의 구체적인 분야·관계·계획 또는 일정·자료 조건을 지우면 같은 답안이 성립하지 않는다.`,topics:'13 타인의 업무 활용. 기술가치가 등장하지만 회계추정 금액 평가 자체를 요구하지 않아 11을 형식적으로 추가하지 않았다.',edition,nonduplication:spec.comparison.map(x=>x.join(': ')).join(' ')},rationale:q.rationale,point_decision:q.point,max_points:sub.criteria.length,fact_ids:q.facts,question_style:'case',topic_ids:q.topics,minimal_sufficient_answer:sub.model_answer,source_checks:sub.requirements.map(r=>({requirement_id:r.id,source_ref_id:r.source_ref_id,source_span:r.source_span,exact_quote_checked:true,source_quote_sha256:hash(r.source_quote),verdict:'pass'})),criterion_checks:sub.criteria.map((c,i)=>({criterion_id:c.id,claim:c.claim,source_ref_ids:c.source_ref_ids,source_checks:c.source_ref_ids.map(id=>({source_ref_id:id,exact_quote_checked:true,quote_sha256:hash(quote(id)),locator:unit(id).locator})),independent_points:1,verdict:'pass',rationale:q.criteria[i][2]})),representative_qa_checks:examples,empty_answer:{expected_points:0,reason:'독립 의미 단위를 하나도 제시하지 않았다.'},unresolved_content_findings:[]});
}
const boundary=[];
const addBoundary=(q,kind,answer,ids,reason)=>boundary.push({set_id:set.id,subquestion_id:q,kind,answer,expected_points:ids.length,met_criterion_ids:ids.map(i=>`${q}.c${i}`),reason,actual_model_grading:'not_run',method:'agent_expected_score_review'});
for(const q of spec.questions){
 for(let i=0;i<q.criteria.length;i++)addBoundary(q.id,'single_element_omission',q.criteria.filter((_,j)=>j!==i).map(c=>c[0]).join(' '),q.criteria.map((_,j)=>j+1).filter(x=>x!==i+1),`c${i+1}의 독립 의미만 삭제했다. 다른 조치에서 그 삭제 의미를 함축하지 않아 남은 기준만 합산한다.`);
 addBoundary(q.id,'generic_only',q.id==='sub1'?'전문가의 적격성, 역량 및 객관성을 평가한다.':q.id==='sub2'?'전문가의 해당 분야를 충분히 이해한다.':'전문가와 커뮤니케이션의 성격·시기·범위와 비밀유지를 합의한다.',[],'일반 목록만 있고 사례의 차이·대상·시점·자료에 대한 적용이 없다. 요구된 구체적 보완의 독립 의미를 충족하지 않는다.');
}
addBoundary('sub1','opposite_condition_with_independent_correct_element','유료 자문 관계가 있으므로 어떤 안전장치도 소용없고 전문가 활용은 항상 금지된다. 다만 토지·건물 평가 경력만으로 기술가치 전문성을 인정하지 말고 바이오 기술 평가 경험을 추가 확인한다.',[1],'관계가 있으면 언제나 금지라는 일반화는 c2/c3을 충족하지 않지만 독립적으로 맞는 적격성 조치 c1은 유지한다.');
addBoundary('sub1','implied_judgment',spec.questions[0].criteria.map(c=>c[0]).join(' '),[1,2,3],'별도 부적절 판단 문구 없이도 필요한 평가·질문 조치가 기존 계획의 보완 필요성을 함축한다. 판단 중복 배점은 없다.');
addBoundary('sub2','delegation_boundary','전문가가 사업계획과 외부 기술사용 계약자료에서 어떤 정보를 사용하는지는 감사인이 이해한다. 다만 사용료 기반 방법과 가정은 전문가만 이해하면 된다.',[2],'직접 맞는 정보의 성격 이해 1점은 유지하고 방법·가정을 전적으로 넘기는 반대 의미만 c1에서 0점이다.');
addBoundary('sub3','timing_boundary','결과는 3월 19일에 전달하도록 합의한다. 가정과 평가 근거를 읽고 검토할 수 있는 보고서로 받으며, 기술정보와 계약단가는 이번 업무에만 사용하고 타 고객 교육에는 사용하지 않도록 합의한다.',[2,3],'보고서일 전날이라는 이유만으로 부모의 3월 10일 검토기한을 충족하지 못한다. 맞는 자료 전달물 및 비밀유지 합의는 각각 유지한다.');
for(const r of review)r.boundary_qa_checks=boundary.filter(x=>x.subquestion_id===r.subquestion_id);
const learningRanges=[
 [learningA,9171,9171,'2021 문제3 공통지문; 교재 p235'],[learningA,9191,9202,'2021 문제3 물음2 상황; 교재 p235'],[learningA,9206,9220,'2021 문제3 물음2 요구 및 물음3·제외 예시; 교재 p236'],[learningA,9268,9275,'2021 문제3 물음2 답안; 교재 p237'],[learningA,9292,9314,'2021 문제3 물음2 전문가 평가 근거 및 물음3 답안; 교재 p238'],
 [advanced,5087,5122,'고급연습 p155 문제15 FSS/2311-04 종속기업투자주식 과대계상 변형의 공통사실과 물음1·2'],[advanced,5124,5156,'고급연습 p156 물음3·4 및 해설. 회사가 의뢰한 경영진측 전문가이며 KGA500 A49의 정보원천이다. 신규 감사인측 전문가의 직접 근거로 전용하지 않고 유사 평가 관점만 참고'],
 [advanced,7031,7052,'고급연습 p214 2023 GS1 문제5 전문가 활용 사례·물음1~3; 이미 수행한 업무의 적합성 평가와 구별'],[advanced,7056,7076,'고급연습 p215 위 GS1 해설. 620.12 평가 및 법규위반·강조사항 요구는 이번 득점 범위에서 제외']
];
const learning=learningRanges.map(([file,a,b,description])=>{const u=cat.units.find(u=>u.file===file&&u.startLine<=a&&u.endLine>=b);if(!u)throw Error(`learning ${a}-${b}`);return{source_unit_id:u.id,file,page:u.page,start_line:a,end_line:b,description,quote:lines(file,a,b),quote_sha256:hash(lines(file,a,b)),file_sha256:hash(fs.readFileSync(file)),authority:u.authority,original_exam_pdf:'원 시험 PDF는 별도로 대조하지 않았다. 학습자료에 수록된 실제 발문·해설과 출제 식별을 대조했다.',frequency_treatment:'기출·FSS 변형 연습·GS 모의를 구별한다. 동일 원물음의 저자 요약·부록·다른 교재 재수록은 추가 출제로 더하지 않는다.'};});
const comparisons=spec.comparison.map(([id,difference])=>{const s=bank.find(s=>s.id===id);if(!s)throw Error(id);return{set_id:id,title:s.title,reviewed_content_hash:hash(JSON.stringify(s)),difference,questions:s.subquestions.map(q=>({id:q.id,prompt:q.prompt,model_answer:q.model_answer,criteria:q.criteria,points:q.criteria.reduce((sum,c)=>sum+c.max_points,0)}))};});
const relatedBank=bank.filter(s=>s.classification.standards.includes('KGA 620'));
const relatedDrafts=inventory.rows.filter(r=>r.questions.some(q=>q.topics?.includes('13')||/감사인측 전문가|전문분야/.test(q.prompt))).map(r=>({...r,comparison:r.id==='case-13-expert-remediation-20260914'?'12·13 결과평가·후속대응으로 신규와 다르다.':r.id==='pilot-13-009'?'9 일반 목록 및8·12 일반 목록으로 새로운 조건 적용과 다르다.':'402 서비스조직 보고서로 620 외부전문가와 주체·절차가 다르다.'}));
const comparisonInventory={method:'machine_inventory_then_agent_semantic_comparison',bank_file:bankFile,bank_sha256:hash(fs.readFileSync(bankFile)),bank_sets:bank.length,draft_inventory_file:inventoryFile,draft_inventory_sha256:hash(fs.readFileSync(inventoryFile)),current_620_sets:relatedBank.map(s=>({id:s.id,title:s.title,reviewed_content_hash:hash(JSON.stringify(s)),prompts:s.subquestions.map(q=>q.prompt),difference:spec.comparison.find(x=>x[0]===s.id)?.[1]??'기존은 일반 책임·활용결정·결과평가/보고서 언급 또는 610 내부감사이며 신규의 착수 전 구체적 평가와 구별된다.'})),related_draft_records:relatedDrafts,notes:['목록상 현재 정본과 같은 ID인 과거 초안은 새로운 중복 후보로 더하지 않았다. 관련 과거 620 초안의 원 파일 발문·모범·criteria도 대조하였다.','현재 관련 은행 외 620 전 문서의 모든 역사적 판본을 새 의미검수 완료한 것으로 주장하지 않는다. 신규와 가까운 요구 및 후보 누락을 확인하기 위한 비교이다.']};
const plan={version:1,topic_id:'13',mode:'adapt_existing_question',objective:'외부전문가의 세부 전문성·객관성 평가, 감사인 자신의 사전 이해와 최초 업무 합의를 구체적 경력·기업관계·방법·일정·기밀조건에 적용한다.',scope:{actors:['다솔바이오의 재무제표 감사인','감사인이 직접 선정하는 외부전문가 서진평가법인'],timing:['2026년 1월 1일 개시 재무제표의 감사, 전문가 선정 및 평가업무 착수 전'],conditions:spec.facts,exceptions:['관계의 존재만으로 무조건 활용 금지라고 단정하지 않고 안전장치 효과를 평가한다. 평가 업무에 필요한 인력·시간은 확보되었다. 모든 합의가 반드시 서면이라는 보편적 의무를 추가하지 않는다.'],required_answers:spec.questions.map(q=>q.prompt),exclusions:['평가금액 계산, 완료된 보고서 오류검증과 620.12·13 후속대응, 620.11의 역할·책임 전체 목록, 경영진측 전문가에 대한 KGA500 절차, 보고의견 유형 판단은 제외한다.']},question_types:['descriptive'],source_unit_ids:[...new Set([...spec.official,...learning.map(x=>x.source_unit_id)])],existing_question_difference:spec.comparison.map(x=>x.join(': ')).join(' '),edition_assumption:edition,unresolved_items:[],status:'ready'};
const latestRanges=[[28636,28662,'620.9~11; PDF683'],[28920,28926,'A14; PDF689'],[28927,28943,'A15 및 A13에 속하는 각주15의 위치; PDF689. A15의 품질관리 판본 차이는 사용하지 않음'],[28949,28997,'A16~A20; PDF690~691'],[28999,29013,'A21~A22; PDF691'],[29014,29080,'A23~A29; PDF691~693; 합의의 형식·관련 의존 문단 문맥'],[29082,29093,'A30~A31; PDF693']];
const design=[{set_id:set.id,version:1,reviewer_id:'agent:/root/followup_sources_b',reviewed_content_hash:hash(JSON.stringify(set)),content_hash:reviewedContentHash(set),plan,basis:{bank_file:bankFile,bank_sha256:hash(fs.readFileSync(bankFile)),source_catalog_file:catalogFile,source_catalog_sha256:hash(fs.readFileSync(catalogFile)),source_catalog_fingerprint:cat.fingerprint,draft_inventory_file:inventoryFile,draft_inventory_sha256:hash(fs.readFileSync(inventoryFile)),comparison_inventory_file:`${dir}/comparison-inventory.json`},lineage:{kind:'new_case_adaptation',previous_set_id:null,previous_question_ids:[],new_subquestion_ids:['sub1','sub2','sub3'],preserves_existing_bank:true},compared_existing_sets:comparisons,learning_source_reading:learning,official_current_edition_comparison:latestRanges.map(([a,b,paragraphs])=>({file:latest,file_sha256:hash(fs.readFileSync(latest)),pdf_file:pdf,pdf_sha256:hash(fs.readFileSync(pdf)),start_line:a,end_line:b,paragraphs,quote:lines(latest,a,b),comparison_result:'해당 범위를 직접 읽고 채점 명제와 적용조건을 대조했다. 품질관리 판본 차이와 각주 소유는 source_boundaries에 별도로 기록한다.'})),source_evidence:source_refs.map(r=>({source_unit_id:r.id,file:r.file,file_sha256:hash(fs.readFileSync(r.file)),quote_sha256:hash(r.source_quote),locator:unit(r.id).locator,authority:unit(r.id).authority,quote_boundary:'등록 단위 안의 해당 문단 본문만 정확히 발췌했다. 뒤따르는 소제목·다음쪽 표시·다음 문단 색인은 인용하지 않고 등록 원문은 보존한다.'})),mapping:spec.questions.map(q=>({subquestion_id:q.id,fact_ids:q.facts,objective:q.rationale,prompt:q.prompt,minimal_sufficient_answer:q.criteria.map(c=>c[0]),independent_requirements:q.criteria.map((c,i)=>({criterion_id:`${q.id}.c${i+1}`,claim:c[0],points:1,source_ref_ids:[c[1],...(c[3]??[])]})),necessary_description:'각 사례의 판단을 가르는 대상·시기·자료를 해당 조치에 연결한다. 한 문장이 여러 독립 명제를 충족하면 정수 점수를 합산한다.',inference_burden:q.rationale,point_decision:q.point,decision:'유지',question_style:'case',topic_ids:q.topics})),facts_chars:[...spec.facts.join('\n')].length,facts_measure:'facts text LF join, Unicode codepoints, spaces included',source_boundaries:{manual_scope:'9·10·11/A14/A17~A22의 직접 인용은 등록 2025 전사 본문이다. 2026 PDF683,689,690,691,693을 렌더해 문단·열거·쪽 경계도 실제 확인했다. 2026 A20은 PDF690~691에 걸치며 기타 용역/서면진술 문구까지 읽었다. A15 뒤 각주15는 앞의 A13 끝 문장에 속하므로 A14 또는 A15의 득점 의존으로 연결하지 않았다. A15 말미의 품질관리체계 용어 차이가 있어 2025/2026 전체 문구가 동일하다고 주장하지 않는다.',dependency_context:'11의 자동 의존성 중 A26~A31 targetId=null 및 A23~A25 학습요약 연결은 자동 패킷 완결을 뜻하지 않는다. 2026 전문에서 A23~A31을 직접 읽어 형식·서면 예외와 커뮤니케이션·비밀유지 문맥을 해결했으며 11(c)(d) 직접 본문으로 필요한 명제는 완결된다. A21의 A7은 전문지식을 얻는 여러 경로에 관한 예시이고 이 물음의 득점은 A22에 열거된 무엇을 이해하는지에 한정된다.',identification_correction:'초기 상위 agent 통지에서 OCR 장식 12를 문제번호로 오인했다. 원문 p235의 문제3 및 cpa_exam:2021:3:2/:3:3의 원발문 기록을 다시 대조하여 바로 정정했다. 최종 설계는 문제3으로만 식별한다.'},unresolved_content_findings:[]}];
const officialProvenance={method:'existing_official_transcription_reused_and_current_pdf_read',agent:'agent:/root/followup_sources_b',human_review_performed:false,new_official_transcription_created:false,registered_files:[...new Set(source_refs.map(x=>x.file))].map(file=>({file,sha256:hash(fs.readFileSync(file))})),current_pdf:{file:pdf,sha256:hash(fs.readFileSync(pdf)),extraction:latest,extraction_sha256:hash(fs.readFileSync(latest))},visuals:[683,689,690,691,693].map(page=>{const file=`${dir}/sources/kga620-page-${page}.png`;return{file,sha256:hash(fs.readFileSync(file)),source:pdf,page,command:`pdftoppm -f ${page} -singlefile -scale-to 1500 -png`,inspection:'agent가 실제 화면에서 해당 본문·열거·쪽 경계 확인'};}),notes:['PDF 이미지는 기존 raw 계보의 원PDF로부터 이 배치에 생성한 파생 검토자료이다. root의 최종 raw 수집 매니페스트에 함께 연결한다.','공식 웹 자료를 새로 내려받은 것이 아니라 기존 공식 PDF 보존본을 직접 대조했다. 최종 source 수집과 현행 게시 확인은 상위 배치 기록과 결속한다.']};
const e=dataset.elements.find(e=>e.id===spec.coverage.element_id),oc=dataset.occurrences.filter(o=>e.occurrence_ids.includes(o.id)),records=dataset.records.filter(r=>oc.some(o=>o.record_id===r.id));
const q=set.subquestions.find(q=>q.id===spec.coverage.question);
const coverage=[{element_id:e.id,set_id:set.id,subquestion_id:q.id,criterion_ids:spec.coverage.criteria,relationship:spec.coverage.relationship,reason:spec.coverage.reason,review_status:'needs_review',target:{file:`${dir}/sets.json`,scope:'draft'},source_unit_ids:['src-be9a2d37235fc0068f'],original_question_ids:e.exam_questions,source_record_ids:records.map(r=>r.id),frequency_kind:'exam',reprint_treatment:'2021 원물음 1회. 저자 요약·동일 원물음의 타 교재 재수록은 별도 횟수에 합산하지 않는다. 고급연습 FSS 변형·2023 GS1을 이 기출의 득점 범위로 합산하지 않는다.',source_locations:learning.filter(x=>x.file===learningA).map(x=>({file:x.file,start_line:x.start_line,end_line:x.end_line,page:x.page})),snapshot:{question_hash:hash(JSON.stringify(q)),question_source_hash:hash(JSON.stringify(set.source_refs)),question_metadata_hash:hash(JSON.stringify({question_style:q.question_style,topic_ids:q.topic_ids})),element_hash:hash(JSON.stringify(e)),source_record_hashes:Object.fromEntries(records.map(r=>[r.id,hash(JSON.stringify(r))])),target_file_sha256:null},provenance:{agent:'agent:/root/followup_sources_b',human_review_performed:false,element_file:elementFile,element_file_sha256:hash(fs.readFileSync(elementFile)),original_records:records,occurrences:oc,manual_reason:'원발문 L9216~9220의 예시 제외와 해설 L9303~9306의 나머지 세 대안 중 두 개 요구를 직접 대조했다. 새 비밀유지 단일 항목은 전체 요구를 충족하지 않아 partial이다.'}}];
const write=(f,v)=>fs.writeFileSync(`${dir}/${f}`,JSON.stringify(v,null,2)+'\n');
write('comparison-inventory.json',comparisonInventory);design[0].basis.comparison_inventory_sha256=hash(fs.readFileSync(`${dir}/comparison-inventory.json`));
write('sets.json',[set]);coverage[0].snapshot.target_file_sha256=hash(fs.readFileSync(`${dir}/sets.json`));
write('design.json',design);write('review.json',review);write('qa.json',qa);write('qa-boundaries.json',boundary);write('coverage-proposals.json',coverage);write('sources/provenance.json',officialProvenance);
const files=[...new Set([latest,pdf,learningA,advanced,...source_refs.map(x=>x.file),...officialProvenance.visuals.map(x=>x.file),`${dir}/sources/provenance.json`])];
write('source-files.json',files.map(file=>({file,sha256:hash(fs.readFileSync(file))})));
console.log(JSON.stringify({sets:1,questions:3,points:set.subquestions.map(q=>q.criteria.length),facts_chars:design[0].facts_chars,qa_rows:qa.length,boundary_rows:boundary.length}));
