import fs from 'node:fs';
import {createHash} from 'node:crypto';
const D='cpa_uploader/drafts/case-trio-2026-09-14',dir=`${D}/a`;
const read=f=>JSON.parse(fs.readFileSync(f,'utf8')),hash=x=>createHash('sha256').update(x).digest('hex'),fh=f=>hash(fs.readFileSync(f));
const sets=read(`${dir}/sets.json`),design=read(`${dir}/design.json`),qa=read(`${dir}/qa.json`),s=sets[0],d=design[0];
const expected={sets:'b3c4d736b38e56f4c60e6690f02bcab580deeed0c6455a344a1dd51ad26272c6',design:'575bc12b4b1b9528769ff91b6945a54bfcd720f38fdc24b1700d749bd1d63ca8',review:'d12e61479135cf1b3cf83d9e6b218b803593342caac56b5694fe1844c38ab852',qa:'f65701e324fb01e6b99f9bb07ce014e17b51b9c3d4856409cf3c095113c3542e'};
for(const[k,h]of Object.entries(expected))if(fh(`${dir}/${k}.json`)!==h)throw Error(`reviewed file changed ${k}`);
const cat=read(`${D}/source-catalog.json`),bank=read(`${D}/bank-before.json`),errors=[];
const sourceChecks=s.source_refs.map(r=>{const text=fs.readFileSync(r.file,'utf8'),u=cat.units.find(x=>x.id===r.id);const exact=text.includes(r.source_quote),sameHash=hash(r.source_quote)===r.content_hash;if(!exact||!sameHash||!u)errors.push(r.id);return{source_ref_id:r.id,file:r.file,file_sha256:fh(r.file),source_quote_sha256:hash(r.source_quote),exact_file_substring:exact,hash_matches:sameHash,registered_unit_exists:!!u,current_pdf_text_and_visual_comparison:'pass',locator:r.source_span};});
const criterionRationales=[
 ['520.6의 종결 분석 의무는 상반기 위험평가 분석·세부테스트로 대체되지 않는다. A19는 유사할 수 있다는 설명이지 생략 허용이 아니다.','하반기 판매구조가 바뀌었다는 기업 이해와 최종 매출 구성·이익률을 대조하는 전반적 결론 목적은 520.6/A17에 부합한다. 개별 결론 확인과 전반적 일관성에 중복 점수를 붙이지 않는다.'],
 ['출하 감소·단가 불변과 기말 매출 급증의 관계는 발생 또는 기간귀속 위험을 추론할 근거이며 확정 오류 증거는 아니다. 두 대안 중 하나와 관계의 의미만 요구한다.','기말 집중 매출의 인수일·실제 출하와 기록일 대조는 발생·기간귀속 위험에 직접 대응하는 절차이다. 520.A18/7 및315.37에 따른 추가 조사와 계획 보완으로 하나의 실질 조치를 평가한다.'],
 ['520.A20은 감사 중 입수한 다른 증거를 고려하여 경영진 답변을 평가할 수 있다고 명시한다. 반드시 새 외부증거를 요구하는 을의 일반화는 배척된다.','계약종료 및 자체 운송의 실제 이행 자료를 비용 감소·전환 시점과 연결하는 증거 평가는 520.7/A20에 부합한다. 사실관계는 이미 다른 감사 중 검증된 자료임을 제공하되 설명이 확실히 맞다는 결론을 주지 않는다.']
];
const questionReviews=s.subquestions.map((q,i)=>({set_id:s.id,subquestion_id:q.id,verdict:'pass',fact_dependency:{facts:d.subquestions[i].fact_ids,verdict:'case',rationale:i===0?'최종 정보와 하반기 판매구조 변화를 연결해야 두 번째 점수를 얻는다. 일반 종결 의무만 쓰면 1점이므로 일반론으로 같은 만점은 성립하지 않는다.':i===1?'자료 관계의 비정상성을 해석해 주장 위험과 기말 검사대상·자료를 특정해야 한다. 다른 종류의 변화는 다른 위험·대응으로 이어진다.':'이미 검사한 외부 계약자료와 내부 실제 이행자료가 무엇인지, 전환 시점과 비용 감소를 어떻게 연결하는지 적용해야 만점이다.'},criterion_reviews:q.criteria.map((c,j)=>({criterion_id:c.id,max_points:c.max_points,verdict:'pass',source_ref_ids:c.source_ref_ids,rationale:criterionRationales[i][j]})),point_appropriateness:'2개의 독립 의미 단위에 각 1점. 판단 또는 위험 추론과 구체적 적용의 의미를 구별하며 같은 내용을 반복하여 점수를 더하지 않는다.',overload:'동일 목표의 판단·근거 또는 위험·직접 절차로 한정하여 3개 물음을 별도로 구성했다.',representative_qa:qa.filter(x=>x.subquestion_id===q.id).map(x=>({kind:x.kind,answer:x.answer,expected_points:x.expected_points,met_criterion_ids:x.met_criterion_ids,verdict:'pass',review_reason:x.kind==='wrong'?'부모에 주어진 관계·증거를 근거 없이 배척하거나 반대 처리를 명시하여 어느 독립 기준도 충족하지 않는다.':'첫 독립 명제만 맞고 두 번째 사례 적용/추가절차가 없어 정확히 1점이다.'})),manual_boundaries:d.subquestions[i].local_regression_expectations.map(x=>({kind:x.kind,answer:x.answer,expected_points:x.expected_points,met_criterion_ids:x.met_criterion_ids,verdict:'pass'})),boundary_reasoning:i===1?'구체적 기간귀속 검사만 쓰는 reverse_partial은 자료관계에서 위험을 추론한 설명까지 자동 함축하지 않아 c2만 1점이다. 다른 위험명칭을 모르겠다는 표현 자체를 명시적 반대 위험판단으로 간주하지 않았다.': '별도 부적절 문구가 없어도 해당 조치가 생략 불가/기존 증거 활용을 함축하면 판단을 인정한다. 명시적 반대 결론을 쓰더라도 독립적으로 맞는 자료 연결 설명의 1점은 유지한다.'}));
for(const q of s.subquestions)for(const row of [...qa.filter(x=>x.subquestion_id===q.id),...d.subquestions.find(x=>x.subquestion_id===q.id).local_regression_expectations]){const pts=q.criteria.filter(c=>row.met_criterion_ids.includes(c.id)).reduce((sum,c)=>sum+c.max_points,0);if(pts!==row.expected_points)errors.push(`${q.id}/${row.kind}/point sum`);}
const sourceLocations=d.source_locations.map(x=>{const quote=fs.readFileSync(x.file,'utf8').split(/\r?\n/).slice(x.start_line-1,x.end_line).join('\n');return{...x,file_sha256:fh(x.file),quote,quote_sha256:hash(quote),review_result:'발문·공통지문·해설의 실제 요구를 직접 읽고 사례와 비교했다.'};});
const official=d.official_edition_comparison.map(x=>({...x,visual_independently_read:true,independent_review_result:'본 reviewer가 PDF450/454/455/229의 렌더를 실제 열어 본문·각주 위치를 확인했고, 기록된 2026 텍스트 범위를 다시 읽었다.'}));
const out={version:'independent-agent-content-review-v1',reviewer_id:'agent:/root/followup_sources_b',method:'independent_agent_manual_content_review',human_review_performed:false,paid_api_semantic_review_performed:false,actual_model_grading:'not_performed_by_this_reviewer; parent retains separate Luna evidence',reviewed_at:new Date().toISOString(),status:errors.length?'fail':'pass',file_bindings:Object.fromEntries(Object.entries(expected).map(([k,sha256])=>[k,{file:`${dir}/${k}.json`,sha256}])),scope:{case_count:1,subquestion_count:3,criterion_count:6,representative_qa_count:6,manual_expectation_count:24,fact_characters:[...s.shared_context.facts.map(x=>x.text).join('\n')].length,facts_measure:'LF join, Unicode codepoints, spaces included',all_questions_fact_dependent:true},question_reviews:questionReviews,source_checks:sourceChecks,official_comparisons:official,learning_source_checks:sourceLocations,source_interpretation:{exam:'교재 수록 2018 문제2 물음5는 위험평가·종결 두 단계와 목적을 모두 요구한다. 신규 sub1은 종결 범위만 적용하므로 partial 관계가 적절하다.',advanced:'고급연습 문제6은 2024 제2회 GS 모의고사 문제2이며 물음2는 520.7의 조사절차 일반 목록이다. 기존 증거의 활용이라는 A20 경계는 직접 원발문의 동일 요구로 세지 않고 adjacent로 구별한다.',footnotes:'520.A18의 각주10은 315.37이다. PDF454 하단에서 직접 확인했다. 각주7~9는 A16, PDF450 각주3은 520.5에 속하며 새로운 요구로 편입하지 않는다.',limit:'별도 원 시험 PDF를 새로 확인한 것이 아니다. 교재 수록 실제 지문·발문·해설을 대조하고 공식2026 PDF로 채점 명제를 검증했다.'},comparison_checks:{bank_file:`${D}/bank-before.json`,bank_sha256:fh(`${D}/bank-before.json`),current_sets:['std-points-20260914-82e96243c6aa','pilot-10-007','case-16-other-information-cause-20260914'].map(id=>{const x=bank.find(s=>s.id===id);return{set_id:id,content_sha256:hash(JSON.stringify(x)),reviewed:'부모 사실·발문·모범답안·criteria를 직접 읽음',verdict:'신규의 종결 적용·원인 위험 추론·이미 입수한 증거 활용과 구별'};}),near_drafts:d.near_draft_comparisons.map(x=>({...x,independently_read:true,verdict:'옛 발문·답안의 일반 단계·실증설계·추가 조사와 신규의 구체 조건을 직접 비교하여 차이 확인'})),scope_limit:'모든 과거 초안의 전체 의미 재검수를 주장하지 않는다. 전체 목록에서 근접 요구를 골라 원문을 직접 비교했다.'},resolved_findings:[],unresolved_findings:errors,limitations:['API 실측, DB 또는 정본·공개본 승급 검증은 이 독립 내용 검토 범위 밖이다.','실제 모델의 criterion 판정·허용 편차는 별도 root 실행 결과로 확인한다.']};
fs.writeFileSync(`${D}/a-peer-review.json`,JSON.stringify(out,null,2)+'\n');
console.log(JSON.stringify({file:`${D}/a-peer-review.json`,sha256:fh(`${D}/a-peer-review.json`),status:out.status,errors}));
if(errors.length)process.exitCode=1;
