import fs from'node:fs';import crypto from'node:crypto';
const own='cpa_uploader/drafts/delegated-authoring-2026-09-11/r02/point-policy-v1',read=f=>JSON.parse(fs.readFileSync(f,'utf8')),hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const selected=read(own+'/qa-selection.json'),validation=read(own+'/local-validation-02.json'),input=read(own+'/inputs.json');if(validation.errors.length)throw Error('Unresolved static errors');
const handoff={owner:'plan_procedures',api_calls:0,created_at:new Date().toISOString(),entries:selected.entries.map(e=>({plan_id:e.plan_id,set_id:e.set_id,changed:e.changed,question_file:e.question_file,plan_file:e.plan_file,qa_file:e.qa_file,lineage_file:e.lineage_file,questions:e.questions,hashes:{question:hash(e.question_file),plan:hash(e.plan_file),qa:hash(e.qa_file),lineage:e.lineage_file?hash(e.lineage_file):null},original_qa_cases:input.entries.find(i=>i.plan_id===e.plan_id).qa.cases.length,new_qa_cases:e.new_case_count??0})),validation:{api_calls:0,checks:[{name:'all_42_subquestions_prompt_required_answer_independent_points_source_review',result:'pass',file:own+'/scoring-decisions.md'},{name:'validateQuestionSetV3_verifySourceQuotes',result:'pass',sets:15},{name:'validateQuestionAuthoringPlan_version1',result:'pass',sets:15},{name:'validate_draft_v3_cli',result:'pass',changed_sets:11},{name:'in_memory_153_set_bank',result:'pass',errors:0},{name:'all_original_QA_id_answer_subquestion_preserved',result:'pass',cases:835},{name:'all_expected_verdict_ids_integer_sums',result:'pass',cases:1224},{name:'each_split_component_targeted_full_paraphrase_omission_opposite_boundary',result:'pass'},{name:'current_saved_answer_and_empty_each_subquestion',result:'pass',questions:42}],report:own+'/local-validation-02.json',model_revalidation:'not_run_user_paused'},totals:{sets:15,questions:42,changed_sets:11,unchanged_sets:4,old_points:119,new_points:156,delta_points:37,original_QA:835,new_QA:389,total_QA:1224},status:'local_point_policy_applied_needs_independent_review_no_model_validation'};
fs.writeFileSync(own+'/handoff.json',JSON.stringify(handoff,null,2)+'\n',{flag:'wx'});
let doc='# 담당 15세트 요소별 배점 적용 결과\n\n2026-09-11 사용자 승인 계약에 따라 15세트 42물음을 모두 읽고 11세트를 수정했다. 4세트는 기존 선택을 유지했다. 119점에서156점으로37점 증가했으며 기존 criterion을 재번호화하지 않고 추가 명제에 미사용 ID를 배정했다. 원지문·공식 출처·원답안835개를 보존했다. 새 QA389개를 더했으며 이 합산·형상 검사는 실제 모델 의미검수나 채점이 아니다. API는0회다.\n\n';
doc+='## 독립 의미 단위의 주요 경계\n\n';
doc+='- T08-C의22점은 기존19점안에 맞춘 결과가 아니다. 500.A55는 관련 전문영역의 이해가 포함된다고 하고, A57은 계약 내용 평가가 업무의 성격·범위·목적 적절성을 결정하는 데 도움을 줄 수 있다고 설명한다. A57의 세 사항을 모든 전문가 업무에서 무조건 별도 암기해야 하는 보편적 의무라고 확대하지 않는다. 이 계약 전문가 사례의 원래 발문·모범답안·criterion이 네 이해 내용을 요구했으므로 각 내용을 답할 수 있는 부분을4점으로 나눴다. 성격은 작업 종류, 범위는 평가 대상과 수행 범위, 목적은 수행 이유, 전문영역은 관련 전문 분야의 이해이며 이름만 길게 늘리는 배점이 아니다. 관련 출처는 보존한 src-379ff6e196897bab12(A55),src-4d4957fa581656d0dd(A57),src-5aa72e77f5f4f9d048(A59)다. A59의 발견·결론4특성과 가정·방법·자료9특성은 감사인측 전문가의 대응 특성과 같은 세분 원칙을 적용했다.\n';
doc+='- T07-A의 전기 증거 관련성/신뢰성은 현재 통제와의 연결/증거를 믿을 수 있는지라는 독립 목적이므로2점이고, 질문에 관찰 또는 검사를 결합하는 방법은1점이다. T08-B의 자료 관련성/신뢰성과 같은 구별이다. 관찰과 검사를 모두 요구하는 것으로 바꾸지 않는다.\n';
doc+='- T08-B에서 모집단 명칭을 고르는 내용과 그 자료가 미기록 매출을 포착하는 목적상의 연결은 별도지만, 한 설명이 둘을 충족할 수 있다. 원 답안 두 개가 실제 목적 연결을 포함하여 관련성도 인정했다. 단순 이름 나열에는 관련성을 자동 보충하지 않는다. 원 검수의 복합 0점을 각 부분의0점으로 복제하지 않았으며 자료 신뢰성 확인은 별도다.\n';
doc+='- T10-C는 이미 계산값이 주어져 있으므로 도출 행위의 반복에 새 점수를 주지 않는다. 기대치의 충분한 정확성 평가가 기존 c6의1점이며 발문·claim·critical_facts를 이에 맞췄다. 정확성만 평가한 답, 주어진 계산의 반복, 명시적 잘못된 결론과 옳은 정확성 평가를 별도 QA로 추가했다. 520.A12(c)의 성격·관련성은 목표예산과 예상결과처럼 정보 성격의 분석목적 적합성을 다루는 한 고려요소로4항목 대응을 유지했다.\n';
doc+='- 판단과 그 함축은 분리해서 기록했다. 예를 들어 T08-B의 구체적인 기간 조정 이유와 T10-C의 미완료 보완조치가 종료계획의 부적절성을 명확히 함축할 때 판단 문구 재진술을 요구하지 않는다. 독립 오류는 관련 명제에만 귀속하고 정상인 이웃 점수를 보존한다.\n';
doc+='- T12-C/D에서 총괄이 승인한 세 QA-only 정정도 원답안과 전후값을 각 lineage에 보존했다. C의 수정분개만 확인하면 된다는 답은 추가절차 필요성 판단에도 반대다. D의 책임진술 범위 구별 불필요 답은 판단에도 반대이고, 성실성 불신 결론만 확인한 동의답은20(a)의1점만 충족하며20(b)의 일반화 판단을 함축하지 않는다.\n\n';
for(const e of handoff.entries){doc+='## '+e.plan_id+' · '+e.set_id+'\n\n';doc+='상태: '+(e.changed?'새 후속본 선택 제안':'기존 선택 유지')+'. '+e.questions.reduce((n,q)=>n+q.old_points,0)+'→'+e.questions.reduce((n,q)=>n+q.new_points,0)+'점.\n\n';for(const q of e.questions){doc+='- **'+q.id+' '+q.old_points+'→'+q.new_points+'점**: '+q.rationale+'\n';doc+='  기준 대응: '+q.criterion_mapping.map(m=>m.old_id+'→'+m.new_ids.join('/')).join(', ')+'. 근거: '+q.source_ref_ids.join(', ')+'.\n';}doc+='\n';}
doc+='## 검증과 남은 범위\n\n[로컬 검사 결과](local-validation-02.json)는 원문 인용·문항 형상·계획·메모리 은행 및 QA 전수 보존과 합계를 확인했다. [인계 선택과 해시](handoff.json)에 선택 경로를 고정했다. 새 문항의 모델 의미검수·실제 채점은 사용자 중지 지시로 미실행이며, 과거 검수/채점 기록을 이번 내용의 통과로 승계하지 않는다. 문항은 needs_review/needs_human_review다. 공통 wiki·coverage·manifest·정본·공개본·운영 DB·배포는 변경하지 않았다.\n';
fs.writeFileSync(own+'/scoring-decisions.md',doc,{flag:'wx'});console.log(JSON.stringify(handoff.totals));
