/** Freeze the first-phase N05 handoff hashes. No model calls. */
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
const base=path.resolve('cpa_uploader/drafts/delegated-authoring-2026-09-11/n05');
const read=f=>JSON.parse(fs.readFileSync(f,'utf8'));
const sha=f=>createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const lineage=read(path.join(base,'lineage.json'));
const check=read(path.join(base,'static-check.json'));
if(check.errors.length)throw Error('Static errors remain');
lineage.stage='draft_ready';
for(const s of lineage.sets){s.stage='draft_ready';s.evidence_sha256=sha(s.evidence_file);s.static_check_file=path.join(base,'static-check.json').replaceAll('\\','/');s.semantic_review='not_run';s.live_grading='not_run';s.sha256=sha(s.actual_file);s.plan_sha256=sha(s.plan_file);s.qa_sha256=sha(s.qa_file);}
fs.writeFileSync(path.join(base,'lineage.json'),JSON.stringify(lineage,null,2)+'\n');
const code=['lib/questionV3.ts','lib/questionV3Grading.ts','cpa_uploader/questionSemanticReview.ts','cpa_uploader/questionAuthoringPlan.ts','cpa_uploader/questionDraftInventory.ts','cpa_uploader/questionBankPublication.ts','cpa_uploader/questionSourceCatalog.mjs'];
fs.writeFileSync(path.join(base,'execution-inputs.json'),JSON.stringify({recorded_at:new Date().toISOString(),phase:'draft_ready_no_model',model_calls:0,preflight_input_budget_chars:400000,openai_api_key_present:!!process.env.OPENAI_API_KEY,review_model_env_present:!!process.env.CPA_REVIEW_MODEL,model_policy_file:'cpa_uploader/analysis/reviews/delegated-authoring-2026-09-11/runtime-settings.json',model_policy_sha256:sha('cpa_uploader/analysis/reviews/delegated-authoring-2026-09-11/runtime-settings.json'),review_model_selection:'총괄 정책 gpt-5.6-luna; 이 단계에서 호출 또는 임의 모델 선택 없음',edition_policy_sha256:sha('cpa_uploader/analysis/reviews/delegated-authoring-2026-09-11/edition-policy.md'),bank_sha256:check.bank_sha256,source_file:'cpa_uploader/data/official/kga600-2025-review14.txt',source_sha256:sha('cpa_uploader/data/official/kga600-2025-review14.txt'),code_hashes:code.map(file=>({file,sha256:sha(file)})),note:'코드 해시는 인계 시점 조회값이다. 총괄의 병렬 예산 지원 수정이 있으므로 2차 시작 시 실제 실행 코드와 비교은행 해시를 다시 고정한다.'},null,2)+'\n');
const rows=lineage.sets.map(s=>`| ${s.plan_id} | ${s.set_id} | KGA 600 2025/2026 직접 대조 | \`${s.sha256}\` | 오류 0 | 미실행 | 0 / 미실측 | 고정 비교본·입력 예산 후 2차 | [초안](${path.basename(s.actual_file)}) · [QA](${path.basename(s.qa_file)}) |`).join('\n');
const text=`# N05 1차 인계\n\n**draft_ready: 신규 2세트·5물음·19점·작성자 QA 76사례.** 모델 의미검수·실제 채점·정본 반영은 아직 하지 않았다. 사용자 전체 제작 범위 중 1차 인계이며 검증 완료 선언이 아니다.\n\n| 계획 ID | 실제 ID | 출처·판본 | 초안 버전·SHA-256 | 정적검사 | 의미검수 | 실제 채점 사례 수·불일치 | 남은 일 | 증거 경로 |\n|---|---|---|---|---|---|---|---|---|\n${rows}\n\n두 파일은 총괄의 49행 ID 장부 중 N05/T14-A·T14-B에 대응한다. version 1 계획과 QA·출처 장부의 파일 해시는 [lineage.json](lineage.json)에 기록했다. 실제 문항 JSON의 \`needs_review\`와 \`needs_human_review\` 상태를 유지한다.\n\nN05 17→19점, 전체 당시 잠정 377→379점은 총괄이 수용한 독립 명제 조정이다. T14-B-Q2의 전체감사·부문중요성, Q3의 전체감사/검토·공통 부문중요성을 분리했다. A-Q2는 일반 보완 가능성 중복점을 제거하고 위험평가 관여·문서검토·심각한 우려 경계에 각 1점을 유지했다. [변경 장부](design-changes.json).\n\n[정적 결과](static-check.json)는 인용 일치, version 1 계획, 현재 등록 src IDs, 명제별 정수 배점, QA 판정 수·합계·해시, 초기 활성 비교본과 ID/동일 발문 충돌, 현재 은행+N05의 메모리 검증, extraDirectory를 지정한 탐색을 확인했다. errors는 0이다. 기본 160,000자에서의 API 무호출 입력 준비 실패는 [초기 검사](preflight/default-budget-static-check.json)에 보존했다. A 170,059자·B 203,792자로 당시 B는 코드 상한 200,000자도 넘었다. 총괄이 관련 회귀검사·TypeScript·대상 lint를 마친 명시적 400,000자 지원을 받은 뒤 같은 전체 원문과 비교 은행으로 재확인했고 두 세트 모두 입력 준비가 통과했다. 현재 정적 오류와 review_preparation_issues는 모두 0이며 공식 등록 메타데이터도 확인했다. API 호출은 없었다. 2차에서 최종49 비교은행을 받아 그 입력 해시로 다시 준비한다. 이 수치는 준비용111+N05 기준으로 전체49 비교본의 길이가 아니다.\n\n공식 등록 파일은 이미 존재하는 \`cpa_uploader/data/official/kga600-2025-review14.txt\`, SHA-256 \`22f6a25d59636722831adc8e50f53c1bb4d711cda61a38eee3434ffbe3be957a\`이다. 공용 새 파일 등록·원본 패치 제안은 없다. 공식 2025/2026 PDF 재다운로드 일치,37문단 비교,6개 번호/추출차 설명 및 물리쪽 위치를 [sources](sources/official-comparison.json)에 보존했다. 선택 판본·공식 확인 범위는 [scope-and-sources.md](scope-and-sources.md), S05의 확정 범위와 중요성 용어는 [s05-handoff.md](s05-handoff.md)를 전달한다.\n\n수동 작성본이므로 정식 검수에는 실제 초안 + version 1 계획의 \`--plan\` 경로와 총괄 고정 \`--bank\`를 사용한다. \`evidence-packet-*.json\`은 자동 source packet이 아니므로 \`--packet\`으로 전달하지 않는다. 정답을 결정하는 직접 문단과 의존 문맥은 실제 source_refs와 plan에 포함했다. 각 requirement에는 직접 항목의 인용을 넣고 전체 문단은 source_refs에 남겨 근거를 절단하지 않았다.\n\nQA 76사례는 저장답안·동의 표현·역순·한 문장·무관한 문장 뒤 정답·명제 누락·명시적 반대·빈 답안·경미함/심각함·전체감사/검토·정확히 하나/하나 이상·공통 중요성 경계를 포함한다. A/sub1의 대안만 남겨도 요청 불가가 함축되는 답은 판단점수를 유지하도록 사전 결정했다. B의 업무유형 누락 사례는 중요성 문장에 같은 유형명이 남아 있지 않게 구성했다. 실제 판정·불일치 수는 미실측이며, 같은 설정 3회 확인과 원인 수정·재채점은 2차에서 수행한다.\n\n키는 \`node --env-file=.env.local\`에서 존재를 확인했고 값은 기록하지 않았다. 모델은 총괄의 gpt-5.6-luna 정책을 이어받는다. [실행 입력 해시](execution-inputs.json)는 인계 조회값이며 실제 호출 때 다시 고정한다. 이 패키지의 쓰기는 n05/ 안으로 제한했다. 기존 R01·frequency-priority 원본·정본·공용 출처·coverage·wiki·게시 자료를 수정하지 않았다.\n`;
fs.writeFileSync(path.join(base,'handoff.md'),text);
console.log(JSON.stringify({stage:lineage.stage,sets:lineage.sets.map(s=>({plan:s.plan_id,id:s.set_id,sha256:s.sha256}))}));
